### ISSUE TITLE
看可不可以扩展参数能够指定下载路径 (会有特殊情况)

### ISSUE THREAD

**Issue by michael811125** [tuyoogame/YooAsset#105]
![D6T88D435NK0NSIEY{MJ~D6](https://user-images.githubusercontent.com/30960759/236366707-e1a45057-5a6a-481f-aac2-3d9f979ce100.jpg)

如图：图片是暂时示意的改法, 主要是 pc 端会有特例情况是, 下载的档案会希望跟著执行档路径走 (一整个资料夹一起), 所以会有需求改成 Application.dataPath 为主要下载路径 (Sandbox 目录结构不变), 当然没有特殊需求默认下就不会特别进行修改。

看是不是修改方法有参数可以带入指定下载路径, 或者说透过 interface 进行 override 重新实作下载路径 (可以自行重新定义至哪一个持久化路径)。

**Comment by gmhevinci** [comment]
参见1.4.13版本 https://github.com/tuyoogame/YooAsset/releases/tag/1.4.13
