### ISSUE TITLE
AddressByFilePath 和 没有开启Enable Addressable 有什么区别？

### ISSUE THREAD

**Issue by RouderSky** [tuyoogame/YooAsset#106]

**Comment by gmhevinci** [comment]
Enable Addressable 代表你开启了 可寻址功能，每个资源都会根据AdressRule生成一个地址（唯一的）。AddressByFilePath 是AdressRule的一种。

**Comment by RouderSky** [comment]
开启Enable Addressable并配置为AddressByFilePath
vs
没有开启Enable Addressable

在load资源的时候使用的路径有什么不同

**Comment by gmhevinci** [comment]
可以参考下教程：https://www.yooasset.com/docs/guide-runtime/CodeTutorial3#%E7%BB%9F%E4%B8%80%E7%BA%A6%E5%AE%9A

**Comment by RouderSky** [comment]
> // 以工程内的音频文件为例："Assets/GameRes/Audio/bgMusic.mp3" 
> // 需要在资源配置界面启用可寻址功能（Enable Addressable）。
> // 配置界面的可寻址规则为AddressByFileName，那么资源定位地址填写文件名称："bgMusic"

看到了 

那如果配置为AddressByFilePath，地址是Assets/GameRes/Audio/bgMusic.mp3吗

**Comment by gmhevinci** [comment]
AddressByFilePath是资源路径，没错

**Comment by RouderSky** [comment]
> 没有开启Enable Addressable

没有开启Enable Addressable时，地址也是Assets/GameRes/Audio/bgMusic.mp3吗

**Comment by gmhevinci** [comment]
没有开启可寻址模式，那么加载地址就是资源文件的全路径。可以带文件后缀也可以不带。
