### ISSUE TITLE
PackRawFile打包得到的原生资源包怎么加载？

### ISSUE THREAD

**Issue by RouderSky** [tuyoogame/YooAsset#107]

**Comment by gmhevinci** [comment]
同学可以看下教程文档：https://www.yooasset.com/docs/guide-runtime/CodeTutorial3

**Comment by RouderSky** [comment]
应该使用LoadRawFileXXX接口吗

**Comment by gmhevinci** [comment]
类似下面代码
IEnumerator Start()
{
    string location = "Assets/GameRes/wwise/init.bnk";
    RawFileOperationHandle handle = package.LoadRawFileAsync(location);
    yield return handle;
    byte[] fileData = handle.GetRawFileData();
    string fileText = handle.GetRawFileText();
    string filePath = handle.GetRawFilePath();
}

**Comment by gmhevinci** [comment]
视频文件 需要配置为原生文件。

**Comment by RouderSky** [comment]
> 视频文件 需要配置为原生文件。

是因为视频文件需要读取byte[]吗

**Comment by gmhevinci** [comment]
不一定读取byte数据，视频一般不需要压缩，视频插件直接指定本地文件路径即可播放。

**Comment by RouderSky** [comment]
> 不一定读取byte数据，视频一般不需要压缩，视频插件直接指定本地文件路径即可播放。

打包之后还能直接给路径给视频插件进行加载？

**Comment by gmhevinci** [comment]
视频播放器都支持指定URL地址来播放，包括本地地址。
