### ISSUE TITLE
即使 CancelDownload 还是会持续下载的 Bug 问题

### ISSUE THREAD

**Issue by michael811125** [tuyoogame/YooAsset#109]
![U)U@VT7EVGCPUYH%T6}R$@F](https://github.com/tuyoogame/YooAsset/assets/30960759/471f0aa4-b97a-4789-97fb-6f6644892166)

CancelDownload 有一个 bug, 建议搞一个 cancel callback 再遍历一下 downloaders 进行 abort, 不然我发现他还是会持续下载耗流量, 至于我要继续下载我再重新建立一个下载器了, 至于提到更底层的下载器是共用问题, 就你提到使用引用计数解决遍历 abort。

**Comment by gmhevinci** [comment]
下个版本 实现这个需求。

**Comment by gmhevinci** [comment]
2.0版本开始 下载器支持abort功能了
