### ISSUE TITLE
新版的文档貌似有问题

### ISSUE THREAD

**Issue by ptiand** [tuyoogame/YooAsset#112]
initParameters.SimulatePatchManifestPath = EditorSimulateModeHelper.SimulateBuild("DefaultPackage");

提示找不到SimulatePatchManifestPath

看了下代码好像改成了SimulateManifestFilePath:
initParameters.SimulateManifestFilePath = EditorSimulateModeHelper.SimulateBuild("DefaultPackage");

**Comment by gmhevinci** [comment]
应该是文档还是老的。已经修改了
