### ISSUE TITLE
有计划支持微信小游戏吗

### ISSUE THREAD

**Issue by alex520lq** [tuyoogame/YooAsset#114]
现在使用项目https://github.com/wechat-miniprogram/minigame-unity-webgl-transform转换到小游戏后。虽然资源被缓存了，但是每次进入游戏都会检查到有新资源需要下载。实际上是不会从cdn 下载的，导致在创建下载器到下载成功(从微信的缓存中获取)这一步会等待7,8秒.

**Comment by gmhevinci** [comment]
支持的，可以参考一下配置教程：https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/blob/main/Design/FileCache.md

**Comment by alex520lq** [comment]
这个缓存有个麻烦的点是 每次新启动都是检测不到缓存的，会走下载 流程，虽然下载的资源是从缓存来的。走下载流程这一步就比较耗时了 如果ab数量比较多，会创建很多下载器下载

**Comment by gmhevinci** [comment]
1.5.2版本已经完全支持了微信小游戏

**Comment by fresh08** [comment]
请问这个问题结局了么，webgl平台在会重复检测到更新（实际并没有走下载流程）

**Comment by gmhevinci** [comment]
因为框架层获取不到微信底层的缓存信息，所以推荐折中处理方式。在每个资源版本首次更新的时候，提示玩家游戏正在同步中，只显示进度，不显示下载大小。后续如果资源版本没有发生变化，就跳过该步骤。
