### ISSUE TITLE
webgl平台远程资源加载报错

### ISSUE THREAD

**Issue by hhxiaohei** [tuyoogame/YooAsset#115]
unity2021 最新版的包 配置的远程地址
<img width="565" alt="image" src="https://github.com/tuyoogame/YooAsset/assets/8379629/6e30278d-9a19-419b-b149-4c72ed92e0b3">

但是加载时候会提示
<img width="1198" alt="image" src="https://github.com/tuyoogame/YooAsset/assets/8379629/663bc4a8-8868-4c4a-8dd2-60c07ec2dc24">
<img width="1192" alt="image" src="https://github.com/tuyoogame/YooAsset/assets/8379629/f1faa394-47a5-47b2-a23b-ead55541bab4">

切换到别的平台却正常,真的很纳闷

**Comment by gmhevinci** [comment]
StreamingAssets目录下的资源，不用放到CDN上。只需要放到网站下面即可。

**Comment by JasonXuDeveloper** [comment]
你好，是这样的：
使用OfflinePlayModeParameters初始化Package后，mac webgl编辑器下会出现：
`
Failed to get asset bundle from web : /Users/jason/Downloads/JEngine-master/UnityProject/Assets/StreamingAssets/BuildinFiles/6dd4498aec81225630a640aa7eb6728f.bundle Error : Cannot connect to destination host
UnityEngine.Debug:LogWarning (object)
YooAsset.YooLogger:Warning (string) (at Assets/Dependencies/YooAsset/Runtime/Utility/YooLogger.cs:47)
YooAsset.AssetBundleWebLoader:Update () (at Assets/Dependencies/YooAsset/Runtime/AssetSystem/Loader/AssetBundleWebLoader.cs:190)
YooAsset.AssetSystemImpl:Update () (at Assets/Dependencies/YooAsset/Runtime/AssetSystem/AssetSystem.cs:67)
YooAsset.ResourcePackage:UpdatePackage () (at Assets/Dependencies/YooAsset/Runtime/ResourcePackage.cs:47)
YooAsset.YooAssets:Update () (at Assets/Dependencies/YooAsset/Runtime/YooAssets.cs:81)
YooAsset.YooAssetsDriver:Update () (at Assets/Dependencies/YooAsset/Runtime/YooAssetsDriver.cs:13)
`
https://github.com/JasonXuDeveloper/JEngine/issues/471

**Comment by gmhevinci** [comment]
明白了。我这边切换到WEBGL平台，然后再编辑器下测试下offline play mode模式。

**Comment by gmhevinci** [comment]
编辑器切换到web gl平台，然后offline play mode 和 host play mode都测试过，没什么问题。你可以尝试把streamgAssets目录清空看看

**Comment by JasonXuDeveloper** [comment]
> 编辑器切换到web gl平台，然后offline play mode 和 host play mode都测试过，没什么问题。你可以尝试把streamgAssets目录清空看看

在macOS下，测试时打包资源选择了CopyAndClear，然后在webgl下编辑器运行，new了个OfflineParameter，然后就会出现截图内的警告

**Comment by hhxiaohei** [comment]
<img width="421" alt="image" src="https://github.com/tuyoogame/YooAsset/assets/8379629/8969009f-069b-4264-8dd2-5d22f3c4af88">
手工改下此文件内容,版本号随便写低点就行了
