### ISSUE TITLE
单机模式下，Android平台，请问怎么把文件加载路径从StreamingAssets改成persistentDataPath？

### ISSUE THREAD

**Issue by mionewu** [tuyoogame/YooAsset#119]

**Comment by gmhevinci** [comment]
单机模式，会优先搜索沙盒丽的缓存文件，如果不存在会去读取内置文件。

**Comment by tonyxx** [comment]
可以直接把资源复制到对应文件夹，在去读取就好了

**Comment by mionewu** [comment]
我发现加载是走的“获取基于流文件夹的加载路径MakeStreamingLoadPath”，没有经过“获取基于沙盒文件夹的加载路径”，请问改如何修改加载方式为沙盒路径

**Comment by gmhevinci** [comment]
从沙盒里读取资源是出于什么目的和需求呢？

**Comment by gmhevinci** [comment]
请关注下最新发布的1.4.17版本，新增了离线模式下，内置资源拷贝到沙盒的功能。
