### ISSUE TITLE
Downloader下載shader的bundle FailedTryAgain超過指定次數沒有OnDownloadErrorCallback

### ISSUE THREAD

**Issue by CGAngel1** [tuyoogame/YooAsset#123]
![螢幕擷取畫面 2023-06-30 161134](https://github.com/tuyoogame/YooAsset/assets/138201655/35ce24e4-1834-456f-873e-07af67c48d25)
我用預設的三次做下載失敗測試，發現shader的這個資源下載失敗超過三次後不會呼叫OnDownloadErrorCallback，流程就一直卡在嘗試重新下載
其他類型的資源超過次數後都會正常呼叫OnDownloadErrorCallback，想請問是為什麼？
我用的是1.4.5的版本

**Comment by CGAngel1** [comment]
然後這個資源包好像是打包時自動產出來的，沒有在收集器裡面設定過shader相關的東西

**Comment by gmhevinci** [comment]
[1.4.9](https://github.com/tuyoogame/YooAsset/releases/tag/1.4.9)版本新增了一个初始化参数：
InitializeParameters类DownloadFailedTryAgain

**Comment by CGAngel1** [comment]
更新到1.4.17後就正常了，謝謝
