### ISSUE TITLE
编辑器模式下 offline 和host  环境 编译平台WebGL  提示错误404

### ISSUE THREAD

**Issue by mjy-0310** [tuyoogame/YooAsset#124]
![image](https://github.com/tuyoogame/YooAsset/assets/64405310/2ee45a85-a80e-4561-983a-644d7f1a1ac7)

**Comment by gmhevinci** [comment]
可以试下1.5.2版本的web play mode

**Comment by mjy-0310** [comment]
<img width="788" alt="image" src="https://github.com/tuyoogame/YooAsset/assets/64405310/9f2a98ee-fcea-4bab-91fb-e42bd24f1ecb">
web play mode  模式

**Comment by gmhevinci** [comment]
你看下Failed to download日志的错误码

**Comment by mjy-0310** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/64405310/b65dd100-4d38-4b74-985f-4833c864f213)

**Comment by gmhevinci** [comment]
Malformed Request Error误

**Comment by mjy-0310** [comment]
积攒了好多问题 SpriteAtlas中的小图要如何加载  现在的文档介绍写的是通过TexturePacker创建的图集

**Comment by mjy-0310** [comment]
微信小程序情况下 如何预加载tag  我根据文档传入我的tag  一直都没办法获取到

**Comment by mjy-0310** [comment]
Malformed Request Error 有专门设置消息头吗       没有设置过

**Comment by gmhevinci** [comment]
> 请问 SpriteAtlas中的小图要如何加载 现在的文档介绍写的是通过TexturePacker创建的图集 代码显示我已经获取到SpriteAtlas 了 但是我依旧没有办法读取到 里面的小图 另外 由于我打包了图集 我没有将散图打包到ab包中 在没有打包散图的情况下 我使用方法加载到了图集 所以预制体重使用到散图的地方都正常显示了 但是代码加载的图片我怎么尝试都不太成功

unity的图集系统加载方式可以参考太空战机的DEMO

**Comment by gmhevinci** [comment]
> 1.5.3情况 微信小程序情况下 如何预加载tag 我根据文档传入我的tag 一直都没办法获取到 记得最开始的文档似乎是有根据tag来加载资源

通过tag获取到AssetInfo，然后加载接口有针对AssetInfo的方法。

**Comment by longde123** [comment]
> > 请问 SpriteAtlas中的小图要如何加载 现在的文档介绍写的是通过TexturePacker创建的图集 代码显示我已经获取到SpriteAtlas 了 但是我依旧没有办法读取到 里面的小图 另外 由于我打包了图集 我没有将散图打包到ab包中 在没有打包散图的情况下 我使用方法加载到了图集 所以预制体重使用到散图的地方都正常显示了 但是代码加载的图片我怎么尝试都不太成功
> 
> unity的图集系统加载方式可以参考太空战机的DEMO

能具體說下馬

**Comment by gmhevinci** [comment]
> > > 请问 SpriteAtlas中的小图要如何加载 现在的文档介绍写的是通过TexturePacker创建的图集 代码显示我已经获取到SpriteAtlas 了 但是我依旧没有办法读取到 里面的小图 另外 由于我打包了图集 我没有将散图打包到ab包中 在没有打包散图的情况下 我使用方法加载到了图集 所以预制体重使用到散图的地方都正常显示了 但是代码加载的图片我怎么尝试都不太成功
> > 
> > 
> > unity的图集系统加载方式可以参考太空战机的DEMO
> 
> 能具體說下馬

https://www.cnblogs.com/msxh/p/14194756.html 可以看下这篇文章
