### ISSUE TITLE
生成的bundle名字会带有空格

### ISSUE THREAD

**Issue by firefly1991** [tuyoogame/YooAsset#129]
例如 Standard Assets文件夹，中间存在一个空格，如果要将该文件夹下的某个资源打成bundle，使用 bundle name_hash name模式，生成的bundle名称会带有空格，是否处理下将空格替换成其他字符

**Comment by k1104480005** [comment]
有空格时在WebGL加载会报错的

**Comment by gmhevinci** [comment]
2.2版本 已经实现。
