### ISSUE TITLE
关于LoadAllAssetsAsync我是否还要做更多？

### ISSUE THREAD

**Issue by xiaomoL444** [tuyoogame/YooAsset#135]
我的理解是location填的是文件夹的位置可是我不管怎么填总是报错？
![image](https://github.com/tuyoogame/YooAsset/assets/69074564/7180696c-cc47-4aaa-af02-0dcde3ca17fe)

**Comment by xiaomoL444** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/69074564/4fdb8131-2794-4d09-a1d4-7f235f9884f6)
首先我已经将它们添加进收集器了

**Comment by gmhevinci** [comment]
LoadAllAssetsAsync 填写的不是文件夹路径。举例，你把配置表文件打进了一个AB里。然后你通过该方法，传入任意一个配置文件路径，即可将AB里的所有配置文件加载出来。

**Comment by xiaomoL444** [comment]
> LoadAllAssetsAsync 填写的不是文件夹路径。举例，你把配置表文件打进了一个AB里。然后你通过该方法，传入任意一个配置文件路径，即可将AB里的所有配置文件加载出来。

好的，谢谢了！

**Comment by eriol24** [comment]
不是太明白這個用法

假設我將一整個Folder放進Collector
裡面都是同一類型的檔案 然後還有很多Sub-folder作分類
我希望LoadAllAssetsAsync可以將所有檔案一併加載作處理

如果需要事先在Script層面Hardcode傳入其中一個檔案的路徑
那麼當有一個Bundle Update令路徑失效或者檔案被刪除時 便需要Update Build?
