### ISSUE TITLE
1.5.3版本打包unity不支持的格式的原生文件会报warning

### ISSUE THREAD

**Issue by JellyHoney** [tuyoogame/YooAsset#138]
在space shooter的demo中的config目录下添加一个命名为"main.bnk"的文件，打包会有warning。
![img_v2_0996bf5a-e1bc-46ec-812f-2af977f2ba5g](https://github.com/tuyoogame/YooAsset/assets/24643386/cb6ff250-c1d8-4057-85a5-f61b687a78b5)

看了下改动，应该是https://github.com/tuyoogame/YooAsset/commit/254da59b7addb220397b454c2c0555b8bc9e6913 改出来的。

**Comment by gmhevinci** [comment]
对于unity无法识别的类型，需要修改为.bytes结尾。或者将bnk文件按照原生文件打包。

**Comment by JellyHoney** [comment]
> 

改成.bytes是可以。
不改成.bytes的话，按照原生文件打包（规则用PackRawFile）一样会有warning

**Comment by JellyHoney** [comment]
> 对于unity无法识别的类型，需要修改为.bytes结尾。或者将bnk文件按照原生文件打包。

改成.bytes是可以。
不改成.bytes的话，按照原生文件打包（规则用PackRawFile）一样会有warning

**Comment by gmhevinci** [comment]
验证修复了。非常感谢反馈
