### ISSUE TITLE
打包場景時會多包進我不想要的垃圾

### ISSUE THREAD

**Issue by CGAngel1** [tuyoogame/YooAsset#139]
我在專案裡有兩個很類似的場景
A是用來測試的，裡面會有很多不想被打包用的測試資源
B是A測試完畢後去除不必要的資源後的正式版

在收集器裡面我只設定要打包B這個場景，但是打包時總是會包到A裡面的垃圾，想請問有辦法解決嗎？

(我不想要被打包的垃圾)
![image](https://github.com/tuyoogame/YooAsset/assets/138201655/2121f2de-344c-472f-95fd-220f2e58de0f)

(A場景)
![1](https://github.com/tuyoogame/YooAsset/assets/138201655/b344e110-2d4f-478f-9ac8-f80bf20b3751)

(B場景)
![2](https://github.com/tuyoogame/YooAsset/assets/138201655/27685161-d391-47c5-98ea-1e5e149b00a5)

**Comment by CGAngel1** [comment]
我是用1.5.1的版本

**Comment by gmhevinci** [comment]
资源构建是依赖于引擎底层接口提供的引用关系。我怀疑是一些资源对象有冗余引用。例如：材质球

**Comment by gmhevinci** [comment]
在Project目录下，对想查看依赖资源的文件，右键使用Select Depends可以查看所有引用资源。

**Comment by CGAngel1** [comment]
找到原因了，原來是不能用複製的場景，不然會依賴，謝謝！
