### ISSUE TITLE
使用1.5.3後的一些問題

### ISSUE THREAD

**Issue by eriol24** [tuyoogame/YooAsset#141]
我是直接在Addressable 1.12.14 版本轉移過來YooAsset 1.5.3
Unity版本 2021.3.16f1
面向iOS及Android
體感是正面的 但還是有些問題想問問

1. Addressable有一個addressables_content_state文件將上一次完整Build Bundle的Version緩存
所以Build App也會有這個Version緩存 導致只要Version名稱變更後, 需要完整Build Bundle之後才Build App
YooAsset會有這個問題嗎 ?

2. 不論使用FullRedundancySharedPackRule或是ZeroRedundancySharedPackRule
有一部份Scene會出現類似Missing LightingData的問題, 令整個Scene會變黑
這個問題Addressable不會出現, 會是什麼原因呢 ?

3. ScriptableBuildPipeline為什麼不能在ForceRebuild出現 ?

4. ShaderVariant收集後, 我開了一個Collector加入它, 也需要在Graphics->Preloaded Shaders中加入嗎 ?

5. 當這些流程都做完 :
YooAssets.Initialize
DefaultPackage.InitializeAsync
DefaultPackage.UpdatePackageVersionAsync
DefaultPackage.UpdatePackageManifestAsync
DefaultPackage.CreateResourceDownloader並下載所有Bundle
第二次使用DefaultPackage.UpdatePackageVersionAsync會出現HTTP 404的問題要怎麼解決 ?

6. 使用Addressable和UniTask進行下載或加載Scene
不定時不限設備會出現這個Error導致卡死
"Reentering the Update method is not allowed"
YooAsset有否避免這個問題? (目前還未有)

感謝

**Comment by eriol24** [comment]
2 & 3.
證實了是BuiltinBuildPipeline的問題
當在BuiltinBuildPipeline ForceRebuild後
沒有任何變動後再在ScriptableBuildPipeline IncrementalBuild便解決了

**Comment by gmhevinci** [comment]
1. YOO应该不存在，只要保证每次构建版本号变化（递增）即可。
2. 和你使用的引擎有关，由于内置构建管线官方已经不维护了。所以unity2021版本开始推荐使用SBP构建。
3. 这个问题，我们后期会进行优化，在ForceRebuild的时候，关闭SBP的缓存或自动清理掉。
4. Proload一般没有特殊需求，是不需要添加的。
5. HTTP 404问题一般是网络原因，可以把失败链接复制到浏览器看下。
6. 这个问题我会咨询我们另一位精通UniTask的专家帮你解答。
