### ISSUE TITLE
如何加载 unity .asset资源

### ISSUE THREAD

**Issue by 9a6c** [tuyoogame/YooAsset#142]
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/1a9c10de-956f-494a-a641-32c05ea81b0e)
我想使用LoadAssetFileAsync去加载发现并没有这个api
然后使用AssetOperationHandle handle = LoadAsset.Instance.Package.LoadAssetAsync<EsRowDataTable>(sheetClassName);去加载，加载处理的内容是空的
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/c29b4b53-5d4a-40b6-ba38-70687c67b3d4)

希望可以给个例子， 希望例子是异步的,因为webgl好像不支持同步, 我尝试使用了LoadAssetSync有报错

**Comment by Mz915** [comment]
补充：使用LoadAssetSync  可以在编辑器中加载出来，但是打出的webgl 运行起来有报错(大概意思是不支持同步方法)，需要使用异步的方式

**Comment by gmhevinci** [comment]
是的。WEBGL平台不支持同步方法。

**Comment by gmhevinci** [comment]
理论上异步方法也没有问题，你可以看下返回的handle的status字段和isDone字段

**Comment by 9a6c** [comment]
我尝试打印它， status是 None ,isDone是 false， yield return handle 好像不会等待它完成后在执行， 如何等待它呢？

**Comment by gmhevinci** [comment]
WEBGL平台理论上是支持协程的，不行的话，你可以注册完成回调方法。

**Comment by 9a6c** [comment]
用不了回调的方式，主要是这里必须要同步等待这个异步结果， 注册回调的方式还是异步，无法解析数据。。。
主要是我使用的这个插件需要有数据才能解析(如下图这些代码都是自动生成的)
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/325b1638-2f05-4afb-a5ca-80cea495b5f6)

我看了同步和异步的方法，最后都是调用LoadAssetInternal， 只是同步方法会调用WaitForAsyncComplete， 而异步方法是直接返回， 我在外面使用 yield return handle;  好像并不会等待操作完成后在继续，好像是直接继续执行的
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/c8e4bc60-a281-4243-b836-c370a69f43df)

放弃了，webgl好麻烦啊
