### ISSUE TITLE
Streaming Assets Root 能否提供自定义路径？

### ISSUE THREAD

**Issue by fanhaining** [tuyoogame/YooAsset#143]
![image](https://github.com/tuyoogame/YooAsset/assets/17611077/d0d831fc-57e4-4d8f-ac70-be6a8a7616aa)
目前这个路径写死了改不了，DefaultYooFolderName也是const string无法修改

**Comment by gmhevinci** [comment]
DefaultYooFolderName可以做成可配置。下个版本发布

**Comment by tonyxx** [comment]
这个我之前是复制到本地，然后直接改成自定义路径了，不过更新后，需要重新改，新版本可以修改最好了

**Comment by gmhevinci** [comment]
[1.5.0](https://github.com/tuyoogame/YooAsset/releases/tag/1.5.0) 版本里，初始化的时候可以自定义BuildinRootDirectory地址。
