### ISSUE TITLE
资源收集希望嵌套不同规则

### ISSUE THREAD

**Issue by lyualvin** [tuyoogame/YooAsset#145]
例如一个主文件夹，大部分资源是按照以父文件夹为一个bundle作为规则，但是某些文件占用过大，希望以单独文件形式打包。
当然可以把这个文件夹放到其他地方，新开一个Collector，但是需求可能是动态的，也会涉及到代码加载资源路径修改，所以换目录不是一个完美方案。或者有其他建议吗？

**Comment by gmhevinci** [comment]
这个需求比较简单：可以自己扩展一个PackDirectory。在自定义规则里，检测超大文件，然后给与单独的bundle名称。

**Comment by gmhevinci** [comment]
参考文档：https://www.yooasset.com/docs/guide-editor/AssetBundleCollector
