### ISSUE TITLE
资源量大的时候启动非常慢，打包编辑器环境也非常慢，2-3分多钟这是受不了的，bytes文件大概5M左右

### ISSUE THREAD

**Issue by yingnierxiao** [tuyoogame/YooAsset#148]
![image](https://github.com/tuyoogame/YooAsset/assets/3435706/67e52caa-abf4-483e-977d-8a83f90af053)

看了下这个函数花费了大量时间 
![image](https://github.com/tuyoogame/YooAsset/assets/3435706/68eac9a3-f839-41b5-b797-ab6999ea611c)
25000个文件  1.5G资源
获取资源构建内容耗时：89秒
更新资源包信息耗时：44秒
创建清单文件耗时：593秒  这内部大量使用List做判断效率太低了，可以改成HashSet
构建过程总计耗时：959秒

顺便搭个车，官网是不是挂了，无法访问

**Comment by gmhevinci** [comment]
感谢反馈，我这边优化一下。
还可以优化一下打包粒度，减少AB数量以及主资源数量，可以减少清单构建时间和大小。

**Comment by gmhevinci** [comment]
该问题已经优化，可以关注下个版本。

**Comment by gmhevinci** [comment]
我优化一下，先比较bundle哈希值，再比对bundle name.
