### ISSUE TITLE
计算资源引用关系问题，这个百分百是出问题了吗？已经是结束了，但是还在不断的计算

### ISSUE THREAD

**Issue by yingnierxiao** [tuyoogame/YooAsset#149]
![image](https://github.com/tuyoogame/YooAsset/assets/3435706/61a2ce31-5ef3-4da8-b7ea-0610d1ee0b24)
![image](https://github.com/tuyoogame/YooAsset/assets/3435706/424c90de-83d6-4125-914a-0f4f0e7eccb8)
这种list的判断存在的方式效率真的非常低效

**Comment by gmhevinci** [comment]
该问题已经优化，可以关注下个版本。
