### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by 9a6c** [tuyoogame/YooAsset#152]
目前我有一个主场景+18个子场景，我应该如何处理资源比较合理

主场景+18个子场景， 资源都很大， 如：主场景+1个子场景，出的pc包在5g左右，所以想请问一下，我该如何处理这些资源比较合理, 资源以模型(fbx)资源居多

**Comment by gmhevinci** [comment]
不建议将模型资源放置在场景里，可以通过代码动态加载的方式。主要关心的是打包粒度的划分，如果工程资源量非常巨大，建议分package构建。

**Comment by 9a6c** [comment]
目前场景是其它人搭建， 会把场景给到我们， 他们是做vr的， 我需要做pc和移动端...
动态加载，是指将它做成预制体，动态加载吗？

**Comment by 9a6c** [comment]
我把模型做成预制体，然后将预制体目录添加到包里，然后进行打包，需要很长打包才能完成。

**Comment by 9a6c** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/f051963c-a438-47c7-bdae-adda910e3ba9)
这个错误有影响吗？

**Comment by gmhevinci** [comment]
这个错误看着是引擎底层抛出的断言。

**Comment by 9a6c** [comment]
应该是的，后续打包，没出来过

我还想问一下，打包资源的时间，还可以在优化一下吗？目前已经使用的最新版本

![image](https://github.com/tuyoogame/YooAsset/assets/51264840/deca8453-e6ed-487c-b702-4b14aa1f5050)
打了1个半小时了，还没出来， 我不太清楚是哪里的问题，我打的资源主要是模型和模型贴图等

10代i7差点没带动打资源包
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/10f07fd8-8501-4cef-89e9-6b2c39307f1d)

**Comment by 9a6c** [comment]
当我有多个包时， 我应该如何处理它。
我当前有一个默认包和模型资源包， 然后用yooasset工具打了一个 1.0.0版本的默认包 和 一个1.0.0版本的模型资源包， 然后合并后，上传到服务器1.0.0文件夹中， 这样是否合理， 是否还有更好的处理方法

**Comment by 9a6c** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/dab6aa91-ef3c-4e84-8ad8-ccf5174408e5)
当前俩个包的版本一样， 但是只下载了默认包， 不下载模型资源包

**Comment by 9a6c** [comment]
已找到问题， YooAssets.CreateResourceDownloader 是使用的默认包创建的下载器， 改成YooAssets.GetPackage(packageName).CreateResourceDownloader后一切正常

**Comment by 9a6c** [comment]
如果优雅的退出？ 
需求：在更新资源的时候，可以退出游戏， 想询问一下，是否有什么主意事项， 如果在更新资源时，是否需要其它操作(如：调用某个api中止本次更新)

**Comment by gmhevinci** [comment]
更新资源的时候，杀死进程没有任何影响。可以放心退出。

**Comment by 9a6c** [comment]
ok, 感谢
