### ISSUE TITLE
OperationSystem里面SetFinish()时, 如果_callback有异常, 会不停打印错误log

### ISSUE THREAD

**Issue by gohoyoo** [tuyoogame/YooAsset#154]
理论上只需要加个try就行了 我没试 不知道对不对
if (operation.IsDone)
{
	_removeList.Add(operation);
	try
	{
		operation.SetFinish();
	}
	catch (Exception e)
	{
	}
}

**Comment by gmhevinci** [comment]
我评估了一下，YooAsset代码逻辑里一共有2处地方，和业务逻辑关联的完成回调。我还是推荐业务逻辑端增加try catch捕获异常
