### ISSUE TITLE
WebGL平台無法預先下載及緩存Bundle

### ISSUE THREAD

**Issue by eriol24** [tuyoogame/YooAsset#155]
有個問題想請教一下

剛查了一下WebPlayModeImpl源碼
發現WebGL所有CreateResourceDownloader都是用ResourceDownloaderOperation.CreateEmptyDownloader
是有什麼原因不能先下載所有bundle才開始遊戲嗎?

另外在使用local http-server來測試時
會在LoadAssetAsync才下載bundle
而且每次Load也會看到get請求
所以WebGL是不能cache bundle嗎?

https://docs.unity3d.com/Manual/webgl-caching.html
Unity官方的這個改動我也有做

感謝

**Comment by gmhevinci** [comment]
这个主要是因为webgl平台的特殊性，框架逻辑无法获取到底层的缓存信息。也无法通过File.Exist()方法来判断。所以只能通过unity引擎底层或者微信小游戏底层来缓存。

**Comment by eriol24** [comment]
明白

下載問題可以用UI先遮一遮
另外bundle也能夠cache了

感謝
