### ISSUE TITLE
加载请求增加优先度调度

### ISSUE THREAD

**Issue by c3076802** [tuyoogame/YooAsset#157]
作者们好

   我们正在将我们的资源加载系统迁移到YooAsset，我们自有的加载系统是有一套按加载优先度的简单调度系统，希望能不能YooAsset也能支持，不胜感激，我们会在加载接口透传一个优先度值，然后加载系统按照其排序加载。
具体使用场景，不同项目可能略有不同
1. 场景加载，--> 优先度1
3. 边玩边下，主要界面，UI角色模型 --> 优先度2
4. 边玩边下，剧情和过场动画 --> 优先度3 
5. 边玩边下，场景角色模型 --> 优先度3
6. 边玩边下，场景特效，-->  优先度4
7. 边玩边下，次要界面和Icon和Sprite --> 优先度4
8. 边玩边下，声音和音乐，--> 优先度4
9. 边玩边下，其他未分类资源 --> 优先度5 
10. 后台静默下载 --> 优先度255

不胜感激

**Comment by gmhevinci** [comment]
这个需求我会认真研究一下。后续会在这个issue里交流。

**Comment by gmhevinci** [comment]
update https://github.com/tuyoogame/YooAsset/commit/ce62dbc27f5a067393b7d06425c83b0b2bcbbe4c
priority值越大 其优先级越高
