### ISSUE TITLE
ShaderVariantCollection收集工具的問題

### ISSUE THREAD

**Issue by CGAngel1** [tuyoogame/YooAsset#159]
請問一下SVC收集工具的問題
1. 只會收集要被打包的資源裡有使用到的shader嗎？
2. 每次收集到的shader數量好像不同，48個是我有在editor裡執行過遊戲幾次再做收集，39個則是開啟專案後直接做收集
哪種才是正確的數量
3. 我有一個Shader是要透過程式碼動態加載的，但它沒有被任何資源引用到，不會被收集，所以我創了一顆材質球套上那個Shader，但材質球沒有放到資源打包的路徑下，這時候Shader會被收集工具收集進去嗎？
我之前試過幾次都有被收集到，但昨天重新收集時又沒有被包含進去，想問問它的規則是什麼？如果想要讓Shader能夠被打包該怎麼做？

![螢幕擷取畫面 2023-09-07 101526](https://github.com/tuyoogame/YooAsset/assets/138201655/7c5500e5-ac79-4556-b567-dcde1b81c23c)

**Comment by gmhevinci** [comment]
1. 是的。通过分析主资源对象筛选出所有引用到的材质球。
2. 这个收集方式还是依赖于引擎提供的方法，我会在收集前清空缓存数据，猜测内存里可能有驻留对象，导致收集有误差，不过这个问题不会影响收集结果。
3. 你的思路没有问题，只是差关键一步，需要把创建的材质球配置到收集界面里。可以使用static collector来收集。

**Comment by CGAngel1** [comment]
用static collector收集後可以正常被打包了，謝謝！
