### ISSUE TITLE
FilterRuleData能否添加更多的信息，比如带入AssetBundleCollector

### ISSUE THREAD

**Issue by c3076802** [tuyoogame/YooAsset#161]
作者您好：
     我们在开发中有时候需要目录内过滤掉某些预制，比如只有界面里面只有以Window为结尾的预制才可以设置为主bundle，现在FilterRuleData只有一个AssetPath，IFilterRule实现就不得不将规则写死到代码里面。
我们现在修改了一下将FilterRuleData增加一个AssetBundleCollector的字段，然后我们利用AssetBundleCollector的UserData字段关联我们的一个规则ScriptableObject配置, 以达到目的。
     请问官方实现可以给FilterRuleData附加更多的信息便于过滤吗？
感谢！

**Comment by gmhevinci** [comment]
需求很简单，下个版本我会实现。
