### ISSUE TITLE
目前下载器还不支持进行中任务的暂停和取消

### ISSUE THREAD

**Issue by Enemy-77** [tuyoogame/YooAsset#174]
> 目前下载器还不支持进行中任务的暂停和取消，后面计划引入引用计数来支持下载器暂停或取消。

作者大大说的。
也就是现在的 `PauseDownload` 和 `CancelDownload` 目前可能达不到预期的效果。希望这条`issue`可以帮助和我遇到同样问题的人节省点时间。

**Comment by gmhevinci** [comment]
暂列BUG处理，后续版本支持。

**Comment by gmhevinci** [comment]
关注一下yooasset2.0版本，已经支持该需求（进行中的任务取消）。
