### ISSUE TITLE
请求资源包构建时，可以选择平台打包，就像Asset Bundle Browser一样

### ISSUE THREAD

**Issue by D3090** [tuyoogame/YooAsset#176]
![image](https://github.com/tuyoogame/YooAsset/assets/105858668/59616b1d-5f4d-49b3-ae3b-a82cc42d3fd9)
![image](https://github.com/tuyoogame/YooAsset/assets/105858668/24fba761-9207-4e7e-91fa-e3474860b4f4)

**Comment by gmhevinci** [comment]
可以添加自定义task，然后切换到目标平台。
