### ISSUE TITLE
2.0.1 的 BuiltinBuildPipeline 沒有做 TaskEncryption_BBP 是預期行為嗎?

### ISSUE THREAD

**Issue by HoshikawaRyuukou** [tuyoogame/YooAsset#180]
剛剛在檢查 bundle 時發現沒有被加密到
有實作 FileOffsetEncryption : IEncryptionServices 

後來檢查 2.0.1 原碼發現 BuiltinBuildPipeline 沒有做 TaskEncryption_BBP 
但 1.5.7 有作 TaskEncryption

請問是漏掉了嗎?
![image](https://github.com/tuyoogame/YooAsset/assets/56442272/847f6eca-6704-470d-b602-d0b8d3f0eeae)

**Comment by gmhevinci** [comment]
是遗漏了。很快修复。

**Comment by HoshikawaRyuukou** [comment]
不好意思
這在 2.0.2 還是漏了
