### ISSUE TITLE
2.0版本，异步加载资源返回后Release句柄后调用UnloadUnusedAssets，会无法正常资源回收

### ISSUE THREAD

**Issue by xhaoh94** [tuyoogame/YooAsset#182]
![Snipaste_2023-10-16_15-10-02](https://github.com/tuyoogame/YooAsset/assets/30614075/ad2ef12e-673d-405f-9b15-ec41d240d1c4)
![Snipaste_2023-10-16_15-12-37](https://github.com/tuyoogame/YooAsset/assets/30614075/214c113b-7266-48f3-87eb-5ebc471ade0c)
Update函数里InvokeCallback回调触发后，异步就返回了。而此时_isUnloadSafe还是false。这时候去回收是会被return的

**Comment by gmhevinci** [comment]
代码是这样设置的，防止在资源加载完成的回调方法里去unload资源。

**Comment by xhaoh94** [comment]
> 代码是这样设置的，防止在资源加载完成的回调方法里去unload资源。
这样吗。例如我异步加载DLL后，已经不需要这个资源了，正常不能去unload资源吗？如果是这样我就延迟一帧也行

**Comment by gmhevinci** [comment]
你可以去release handle，然后合适的时机（例如切换场景）去调用package.unloadused()方法释放不在使用的资源。

**Comment by xhaoh94** [comment]
好的
