### ISSUE TITLE
RemoveSpriteAtlasRedundancy脚本导致贴图引用丢失

### ISSUE THREAD

**Issue by xushunwang** [tuyoogame/YooAsset#183]
YooAsset版本：1.5.3-preview pick了 “加入 ExtdBuildTasks 进行 SBP 扩展，修复 Sprite 打包冗馀问题”这个提交。最新的没试过我看这块代码是没变动过的

新建一个脚本绑在预制上
```
public class TestAtlasTexture : MonoBehaviour
{
    public Texture2D texture;
    public Sprite sprite;
}
```
编辑器上这个预制添加上述脚本，并且两个变量都引用同一张图。图片设置为Sprite (2D and UI)格式，并且被打入一个图集(Unity Sprite Atlas V1)。

把这个预制打包并运行的时候动态加载他，会发现texture引用丢失了。
![图片](https://github.com/tuyoogame/YooAsset/assets/3183025/4f06a052-dd60-4404-8bd9-3f3a35b5c2d3)

**Comment by gmhevinci** [comment]
只能复制一份图片作为textuer引用

**Comment by xushunwang** [comment]
> 只能复制一份图片作为textuer引用

那先暂时不用这个了，还是用回我之前那个方案。项目里这种引用方式的蛮多的现在。

**Comment by gmhevinci** [comment]
该issue不用关闭

**Comment by gmhevinci** [comment]
SBP最新的构建管线已经修复了图集冗余的问题。只需要保证精灵图片和SpriteAtlas构建在一个AB即可。
