### ISSUE TITLE
建议在寻址模式下增加AssetPath命名自定义的支持

### ISSUE THREAD

**Issue by st75033562** [tuyoogame/YooAsset#187]
建议在寻址模式下增加AssetPath命名自定义的支持，由此用户可以缩短不必要的全路径，优化清单大小与内存大小

**Comment by gmhevinci** [comment]
可寻址模式下，可以修改打包配置来支持通过asset object name来加载资源对象。

**Comment by gmhevinci** [comment]
引擎底层会根据asset object name去映射asset path，然后去加载资源对下。如果同一个AB里有相同的asset object name，会导致非正常的加载结果。暂时放弃支持。
