### ISSUE TITLE
error bundleInfo.Bundle.Buildpipeline == DefaultBuildPipeline.RawFileBuildPipelineName

### ISSUE THREAD

**Issue by tpctm** [tuyoogame/YooAsset#188]
bundleInfo.Bundle.Buildpipeline == DefaultBuildPipeline.RawFileBuildPipelineName

**Comment by gmhevinci** [comment]
还需要更详细的报错信息，可以贴下堆栈信息吗

**Comment by wdb4tiancai** [comment]
Exception: Cannot load asset bundle file using LoadRawFileAsync method !
YooAsset.ResourcePackage.DebugCheckRawFileLoadMethod (System.String method) (at Library/PackageCache/com.tuyoogame.yooasset@2.0.2-preview/Runtime/ResourcePackage/ResourcePackage.cs:1125)
YooAsset.ResourcePackage.LoadRawFileInternal (YooAsset.AssetInfo assetInfo, System.Boolean waitForAsyncComplete) (at Library/PackageCache/com.tuyoogame.yooasset@2.0.2-preview/Runtime/ResourcePackage/ResourcePackage.cs:562)
YooAsset.ResourcePackage.LoadRawFileAsync (System.String location) (at Library/PackageCache/com.tuyoogame.yooasset@2.0.2-preview/Runtime/ResourcePackage/ResourcePackage.cs:556)
YooAsset.YooAssets.LoadRawFileAsync (System.String location) (at Library/PackageCache/com.tuyoogame.yooasset@2.0.2-preview/Runtime/YooAssetsExtension.cs:154)

**Comment by wdb4tiancai** [comment]
private RawFileHandle LoadRawFileInternal(AssetInfo assetInfo, bool waitForAsyncComplete)
		{
			DebugCheckRawFileLoadMethod(nameof(LoadRawFileAsync));
			var handle = _resourceMgr.LoadRawFileAsync(assetInfo);
			if (waitForAsyncComplete)
				handle.WaitForAsyncComplete();
			return handle;
		}
DebugCheckRawFileLoadMethod(nameof(LoadRawFileAsync)); 为什么加了这一句

**Comment by gmhevinci** [comment]
fix https://github.com/tuyoogame/YooAsset/commit/c3d5c13a8029ab5fb5283e49c5466549fe02be04
