### ISSUE TITLE
如何实现边玩边下

### ISSUE THREAD

**Issue by 9a6c** [tuyoogame/YooAsset#191]
需求：边玩边下，玩家移动，只加载玩家附近的资源

不太清楚如何用YooAsset写， 看文档好像是需要先初始化、获取资源版本、更新资源清单。
然后就可以在游戏中边玩边下了？

**Comment by gmhevinci** [comment]
是的。只要保证本地激活的清单是最新的就可以了。然后使用异步方法加载资源对象，如果资源对象引用的AB再本地不存在，会自动去CDN下载，然后再加载。

**Comment by 9a6c** [comment]
`using System.Collections;
using UnityEngine;
using YooAsset;

namespace Game
{
    /// <summary>
    /// yoo加载封装
    /// </summary>
    public class YooLoad : MonoBehaviour
    {
        private static YooLoad instance;
        private bool initialize = false;

        public static YooLoad Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = FindObjectOfType<YooLoad>();
                    if (instance == null)
                    {
                        GameObject singleton = new GameObject("[YooLoad]");
                        instance = singleton.AddComponent<YooLoad>();
                        DontDestroyOnLoad(singleton);
                    }
                }
                return instance;
            }
        }

        /// <summary>
        /// 是否初始化完成
        /// </summary>
        public bool Initialize { get => initialize; set => initialize = value; }

        /// <summary>
        /// 加载指定标签的所有
        /// </summary>
        /// <param name="tag"></param>
        /// <param name="transform"></param>
        public void LoadAllGameobject(string tag, Transform transform)
        {
            AssetInfo[] assetInfos = YooAssets.GetAssetInfos(tag);
            Debug.Log($"--------------------[{assetInfos.Length}]--------------------");
        }

        public IEnumerator Internal_LoadAllGameobject(string tag, Transform transform)
        {
            yield return null;
        }

        public void LoadGameobject(string location, Transform transform)
        {
            StartCoroutine(Internal_LoadGameobject(YooAssets.GetAssetInfo(location), transform));
        }

        public void LoadGameobject(AssetInfo assetInfo, Transform transform)
        {
            StartCoroutine(Internal_LoadGameobject(assetInfo, transform));
        }

        internal IEnumerator Internal_LoadGameobject(AssetInfo assetInfo, Transform transform)
        {
            //需要从远端下载
            if (YooAssets.IsNeedDownloadFromRemote(assetInfo))
            {
                Debug.LogWarning($"需要从远端下载,{assetInfo.AssetPath}");
                int downloadingMaxNumber = 10;
                int failedTryAgain = 3;
                ResourceDownloaderOperation downloader = YooAssets.CreateBundleDownloader(assetInfo, downloadingMaxNumber, failedTryAgain);
                if (downloader.TotalDownloadCount == 0)
                {
                    Debug.Log("没有需要下载的资源");
                    yield break;
                }

                //开启下载
                downloader.BeginDownload();
                yield return downloader;

                //检测下载结果
                if (downloader.Status == EOperationStatus.Succeed)
                {
                    //下载成功,实例化该物体
                    Debug.LogWarning("下载成功,实例化该物体");
                    yield return Internal_LoadGameobject(assetInfo, transform);
                }
                else
                {
                    //下载失败
                    Debug.LogError($"下载失败：{assetInfo.AssetPath}");
                    //TODO其它处理
                }
            }
            else
            {
                AssetOperationHandle handle = YooAssets.LoadAssetAsync<GameObject>(assetInfo.AssetPath);
                yield return handle;
                GameObject go = handle.InstantiateSync(transform);
                Debug.Log($"Prefab name is {go.name}");
            }
        }

        private void OnApplicationQuit()
        {
            YooAssets.Destroy();
        }
    }
}`

**Comment by 9a6c** [comment]
我目前在进行测试， 遇到了部分问题，  我只要保证资源清单是新的， 然后在游戏中直接去加载物品就可以了， 比如我想加载指定tag的所有物品， 不需要自己创建下载器下载， 然后做加载，   框架在底层已经实现了这部分内容吗？

我需要做的只是保证资源清单是最新的即可？ 在游戏中正常调用 YooAssets.LoadAssetAsync去加载就可以了吗

**Comment by 9a6c** [comment]
我尝试直接加载， 是自动去下载的

其它问题：当bundle文件很大时， 需要下载很久， 尝试从配置单个文件夹收集更改为单个预制体。然后打包， 这个bundle是根据组来进行划分的， 还有其它方式可以让它每个预制体一个包？

![image](https://github.com/tuyoogame/YooAsset/assets/51264840/a6471261-ff6c-411f-9b49-937a741c1a80)

**Comment by 9a6c** [comment]
终于找到了，原来是这里配置的
