### ISSUE TITLE
报错：Exception: Should never get here

### ISSUE THREAD

**Issue by moon2689** [tuyoogame/YooAsset#195]
编辑器模式下，AssetHandle.GetDownloadStatus()获取到的TotalBytes是0，导致报错：Exception: Should never get here
![E1S% 0M1~Z82W3 FJLH{@11](https://github.com/tuyoogame/YooAsset/assets/10527653/d4b71481-0229-4048-baf4-26cd24e5750f)

**Comment by gmhevinci** [comment]
eidtor play mode生成的清单里 bundle size为零导致的。
