### ISSUE TITLE
2.0.3 webgl平台创建webdownload失败

### ISSUE THREAD

**Issue by silingfei** [tuyoogame/YooAsset#196]
文件：WebDownloader.cs  71行

			// 创建下载器
			if (_steps == ESteps.CreateDownloader)
			{
				_requester = (IWebRequester)Activator.CreateInstance(_requesterType);
				_requester.Create(_requestURL, _bundleInfo, _getAssetBundle);
				_steps = ESteps.CheckDownload;
			}
创建无惨构造函数异常

**Comment by michael811125** [comment]
我也遇过，如果透过 Activator.CreateInstance 搭配 HybridCLR 建立实例时，都需要定义无惨构造函数, 如果还发生创建无惨构造函数异常问题，那只能扩展创建方法能够额外表明型态进行 new() 了。

![image](https://github.com/tuyoogame/YooAsset/assets/30960759/69cd3dc9-76a0-407d-b8a6-491a90315a47)

**Comment by gmhevinci** [comment]
https://github.com/tuyoogame/YooAsset/issues/205
