### ISSUE TITLE
资源组名称更改删掉一个字符就弹个保存,体验有些不太好

### ISSUE THREAD

**Issue by coder-lipenghui** [tuyoogame/YooAsset#2]
资源组名称更改删掉一个字符就弹个保存,体验有些不太好 除了冲进json改名字 还有其他比较优雅的方式吗

**Comment by gmhevinci** [comment]
谢谢你的反馈，我这边尽快优化一下

**Comment by coder-lipenghui** [comment]
mac下的bug，windows下面没问题。
untiy:2020.3.21

**Comment by gmhevinci** [comment]
反馈的问题，我们已经做了优化，修改为在编辑窗口关闭的时候自动保存配置。
