### ISSUE TITLE
Assetbundle 无法断点续传

### ISSUE THREAD

**Issue by beibiaoji** [tuyoogame/YooAsset#201]
FindCacheFilesOperation类 方法 UpdateFindBundleFiles对Ab包进行校验，我有一个ab包是没有下完的，有一个.temp文件，这一步在校验ab包之后由于找不到对应的.info文件，会见该temp所在的文件夹删除，具体代码在 VerifyCacheFilesWithThreadOperation中的
      private void VerifyCallback(object obj)
      {
	      VerifyCacheFileElement element = (VerifyCacheFileElement)obj;
	      _verifyingList.Remove(element);
      
	      if (element.Result == EVerifyResult.Succeed)
	      {
		      _succeedCount++;
		      var wrapper = new PackageCache.RecordWrapper(element.InfoFilePath, element.DataFilePath, element.DataFileCRC, element.DataFileSize);
		      CacheSystem.RecordFile(element.PackageName, element.CacheGUID, wrapper);
	      }
	      else
	      {
		      _failedCount++;
      
		      YooLogger.Warning($"Failed verify file and delete files : {element.FileRootPath}");
		      element.DeleteFiles();
	      }
      }

导致后续下载ab时校验temp文件，由于之前已经将该temp文件删除，导致VerifyTempFileWithThreadOperation校验失败，无法实现断点续传

**Comment by gmhevinci** [comment]
版本2.0.3
