### ISSUE TITLE
如果FileNameStyle用的是BundleName，IQueryServices会一直返回true导致无法更新

### ISSUE THREAD

**Issue by LinNaiHao** [tuyoogame/YooAsset#202]

**Comment by gmhevinci** [comment]
版本2.0.3

**Comment by gmhevinci** [comment]
太空战机的工程里，StreamingAssetsHelper.cs脚本里。将CompareFileCRC 修改为true

`/// <summary>
/// 资源文件查询服务类
/// </summary>
public class GameQueryServices : IBuildinQueryServices
{
    /// <summary>
    /// 查询内置文件的时候，是否比对文件哈希值
    /// </summary>
    public static bool CompareFileCRC = false;

    public bool Query(string packageName, string fileName, string fileCRC)
    {
        // 注意：fileName包含文件格式
        return StreamingAssetsHelper.FileExists(packageName, fileName, fileCRC);
    }
}`

**Comment by gmhevinci** [comment]
太空战机的工程里，StreamingAssetsHelper.cs脚本里。将CompareFileCRC 修改为true



```c#
public class GameQueryServices : IBuildinQueryServices
{
    //查询内置文件的时候，是否比对文件哈希值
    public static bool CompareFileCRC = false;
}
```

**Comment by gmhevinci** [comment]
改issue请勿关闭
