### ISSUE TITLE
[Feature Request] 允许自定义打包的输出目录

### ISSUE THREAD

**Issue by tanghuipang** [tuyoogame/YooAsset#203]
目前的设计是每次打包都放入给定版本的文件夹，保证该文件夹里的内容完整，但是这样会导致不同版本间有大量的冗余文件，项目后期资源版本数量多的时候会占用大量的硬盘空间。
希望在生成的文件名带有hash时允许将不同版本放入到同一个文件夹，这样就不会有相同文件重复的情况。可以通过清单文件查询特定版本包含的全部文件，也就可以转换成之前不同版本不同文件夹的存放形式。
如果能重载 BuildParameters.GetPackageOutputDirectory() 方法，就可以自定义打包输出目录到同一个目录。

**Comment by gmhevinci** [comment]
构建的补丁包输出目录还是分开好一些。至于上传CDN资源，可以通过编写版本差异文件工具来减少上传冗余。可以参考Samples工程里的PackageComparatorWindow.cs脚本。
