### ISSUE TITLE
微信小游戏读取原生文件，读取不到问题

### ISSUE THREAD

**Issue by liaoliao0896** [tuyoogame/YooAsset#208]
在微信小游戏打包完成以后运行游戏示例
1.  var downloader = package.CreateResourceDownloader(downloadingMaxNum, failedTryAgain); 
  downloader.BeginDownload();
  yield return downloader;
在下载成功以后读原生文件
 RawFileHandle handle0 = package.LoadRawFileAsync("Assets/AssetPackage/Raw/a.txt");
yield return handle0;
Debug.Log($"Status:{handle0.Status} error:{handle0.LastError} djmadd:{handle0.GetRawFileText()}");
打印结果handle0.Status==Successful 
GetRawFileText里面的filePath==null所以返回了空串

**Comment by gmhevinci** [comment]
看了一下源码，理论上filepath == null 加载器一定是返回失败的。希望再确认一下。

**Comment by gmhevinci** [comment]
RawBundleWebLoader 在steps == CheckFile的时候会判断File.Exsits(FileLoadPath)

**Comment by liaoliao0896** [comment]
我把版本修改到1.5.7,就好了，读取正常了。

**Comment by gmhevinci** [comment]
我看下版本差异

**Comment by tomh520** [comment]
微信小游戏不是不支持File类接口吗？ 为什么还可以使用File.Exists做判断呢

**Comment by gmhevinci** [comment]
请升级到2.2版本。使用微信小游戏 专属的文件系统。
