### ISSUE TITLE
Unity-2020.3.1 YooAsset-2.0.3 导入问题

### ISSUE THREAD

**Issue by bingtanghulu123** [tuyoogame/YooAsset#209]
1·#if UNITY_2020_3_OR_NEWER 宏未生效
![image](https://github.com/tuyoogame/YooAsset/assets/73873790/83af4949-77a8-4767-80e2-79391ab5eee2)
2·这个defaultIndex是无效的 84行encyptionClassName为空值
![image](https://github.com/tuyoogame/YooAsset/assets/73873790/0b9fd068-1b83-465f-9c3f-27836d8e6c9e)

**Comment by gmhevinci** [comment]
建议升级一下引擎的小版本号。每个LTS版本的前期几个小版本号都是非常不稳定的。
