### ISSUE TITLE
建议容器的ContainsKey Add 改为TryAdd

### ISSUE THREAD

**Issue by huangchaoqun** [tuyoogame/YooAsset#218]
![image](https://github.com/tuyoogame/YooAsset/assets/24500684/37794477-c224-4d25-9e0f-85d4aa53c11a)

**Comment by gmhevinci** [comment]
是前者执行效率更高吗？

**Comment by huangchaoqun** [comment]
量级+多线程的情况下用tryadd，editor单线程的话区别不大，主要是优雅，哈哈哈

**Comment by gmhevinci** [comment]
了解了。

**Comment by gmhevinci** [comment]
这个是不是扩展方法？没找到
