### ISSUE TITLE
请问这个打印是什么原因下会触发

### ISSUE THREAD

**Issue by 9a6c** [tuyoogame/YooAsset#222]
1.5.7版本

我最近使用mirror来部署服务端(客户端和服务端同一个工程)

服务端一直打印
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/e25e4762-5ec4-4898-81fd-7bf838cb0a4f)

**Comment by 9a6c** [comment]
用的麒麟服务器，一直打印这个， 是因为unity不支持吗？
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/4e38cf2e-55ea-4f74-9a07-a2874606c9bf)

**Comment by gmhevinci** [comment]
资源下载超时了，建议换个HFS做对照测试。

**Comment by gmhevinci** [comment]
超时判定条件：一定时间内（下载器传入参数）没有接受到任何字节数据

**Comment by 9a6c** [comment]
感谢您的回复，我大体知道原因了， 应该是服务器不允许访问
