### ISSUE TITLE
读取默认加密方法会导致报错

### ISSUE THREAD

**Issue by absences** [tuyoogame/YooAsset#223]
![image](https://github.com/tuyoogame/YooAsset/assets/49706424/21ff2b60-a5fd-46f0-a198-be57cf0b742a)
_encryptionField = new PopupField<Type>(encryptionClassTypes, defaultIndex);
修改为
_encryptionField = new PopupField<Type>(encryptionClassTypes, defaultIndex == -1 ? 0 : defaultIndex);
懒得pull了

**Comment by absences** [comment]
还有构建
 _buildModeField = new PopupField<Enum>(buildModeList, defaultIndex == -1 ? 0 : defaultIndex);

**Comment by absences** [comment]
由于ScriptableBuildPipeline  BuildModes从1开始的
![image](https://github.com/tuyoogame/YooAsset/assets/49706424/6de9c630-d263-4305-a454-b733013ecc91)
![image](https://github.com/tuyoogame/YooAsset/assets/49706424/bae50592-9238-4fcc-965c-d3bac434d22b)
导致错位，需要抽象方法将_buildModeField.value转为对应的EBuildMode

**Comment by gmhevinci** [comment]
感谢反馈，我这边会在下个版本修复。

**Comment by absences** [comment]
_buildModeField = new PopupField(buildModeList, defaultIndex == -1 ? (int)(EBuildMode)buildModeList[0] : defaultIndex);
取枚举列表第一个值，不是0
