### ISSUE TITLE
1.5.7 版本 AssetSystemImpl.Update()遍历IsBusy次数过多，导致过多的耗时

### ISSUE THREAD

**Issue by walesT** [tuyoogame/YooAsset#226]
当_loadingMaxTimeSlice使用默认值long.MaxValue没有限制时，AssetSystemImpl.Update()遍历对每一个_providerList都需要判定一遍IsBusy，并且IsBusy永远为false，这样让_watch.ElapsedMilliseconds获取的次数过多，导致没必要的性能消耗，希望在没有对_loadingMaxTimeSlice有限制时，不需要判断IsBusy，或者降低一下IsBusy的遍历次数。

**Comment by gmhevinci** [comment]
provider完成的时候，直接continue跳过判定。下个版本优化
