### ISSUE TITLE
播放视频文件，必须将初始化参数InitializeParameters.CacheFileAppendExtension=true

### ISSUE THREAD

**Issue by absences** [tuyoogame/YooAsset#228]
不然获取GetRawFilePath没有后缀无法播放
不是bug，解决方案没有提到

**Comment by luducn** [comment]
大佬现在版本没找到这个 能帮帮我吗 哭了

**Comment by absences** [comment]
initParams.BuildinFileSystemParameters.AddParameter(FileSystemParametersDefine.APPEND_FILE_EXTENSION, true);
