### ISSUE TITLE
可以在外部下载热更新资源吗？

### ISSUE THREAD

**Issue by alex520lq** [tuyoogame/YooAsset#233]
现在使用Unity的方式是将Unity嵌入到原生App中，在app某些环节拉起Unity，想在App先预下载Unity需要的热更资源放到指定的目录下，进入Unity的时候直接使用，达到一个预下载的过程。缩减进入游戏时间

**Comment by gmhevinci** [comment]
/// <summary>
        /// 创建资源导入器
        /// 注意：资源文件名称必须和资源服务器部署的文件名称一致！
        /// </summary>
        /// <param name="filePaths">资源路径列表</param>
        /// <param name="importerMaxNumber">同时导入的最大文件数</param>
        /// <param name="failedTryAgain">导入失败的重试次数</param>
        public ResourceImporterOperation CreateResourceImporter(string[] filePaths, int importerMaxNumber, int failedTryAgain)

可以把资源打成一个ZIP包，然后下载解压到本地。进入游戏初始化package之后，使用上面的方法导入预先下载的资源。

**Comment by xianliangDev** [comment]
CreateResourceImporter API有具体的使用案例吗，为什么
