### ISSUE TITLE
在打包WEGL之后加载报错

### ISSUE THREAD

**Issue by AlianBlank** [tuyoogame/YooAsset#237]
![image](https://github.com/tuyoogame/YooAsset/assets/1950044/873ffaad-ec72-4ada-9f91-b0ba3b807aa3)
以上是错误日志。
已经尝试：
1. 修改改类的构造函数。已有。但无效
2. 关闭裁剪。把裁剪等级设置为low 。结果无效
3. 增加Link.xml 设置YooAsset 程序集为全保留。结果无效。

使用环境：
Unity 2019.4.40f1 国际版
HybridCLR 5.0.0 
YooAsset 2.1.0

还会报错一个：
![image](https://github.com/tuyoogame/YooAsset/assets/1950044/0956f7b6-12b1-48ee-8501-cde24c685d4a)

**Comment by gmhevinci** [comment]
禁用HybridCLR会有效吗？之前使用HCLR使用反射创建类，需要声明该类的默认构造函数。

**Comment by gmhevinci** [comment]
https://github.com/tuyoogame/YooAsset/issues/205

**Comment by AlianBlank** [comment]
我已经解决了该问题。需要手动创建一个AOT的引用。不能让Unity裁剪掉所有的代码
