### ISSUE TITLE
新增功能：微信小游戏平台，资源下载器支持底层缓存查询 无法找到引用报错

### ISSUE THREAD

**Issue by su9257** [tuyoogame/YooAsset#238]
![image](https://github.com/tuyoogame/YooAsset/assets/20715825/5dcc4907-f27d-40d0-9649-aeae1478f79e)
![image](https://github.com/tuyoogame/YooAsset/assets/20715825/aaabcb4c-80ba-4fbc-a917-dd07c6bc09bb)

如果走UPM包管理，无法添加外部引用程序集，造成引用丢失报错。
对于依赖第三方应用的功能，可否添加可重写的函数，由外部重写，这样既可以不更改原有的程序集划分，又可以添加新的功能？

**Comment by gmhevinci** [comment]
好的。下个版本我会提供新接口

**Comment by dongyiqi** [comment]
> 好的。下个版本我会提供新接口

这个有进展么？

**Comment by gmhevinci** [comment]
该功能已经提交了
https://github.com/tuyoogame/YooAsset/commit/370329b07d376c302eff4a57c6f519287cf1b5cb

**Comment by gmhevinci** [comment]
2.2 版本已经完美适配微信小游戏插件
