### ISSUE TITLE
ab包加载的资源和编辑器模式下载的资源效果不同

### ISSUE THREAD

**Issue by 9a6c** [tuyoogame/YooAsset#240]
这是什么原因呢
![c933cdb3b9867c2c599c87673524140](https://github.com/tuyoogame/YooAsset/assets/51264840/e70017b6-0179-4e0b-8fad-ffc5ce46b4bd)
![366e60ed4cc43ab25c8a75cece4ac33](https://github.com/tuyoogame/YooAsset/assets/51264840/3fdc14af-b5e7-49a8-8de9-d74a39fc8abd)

**Comment by gmhevinci** [comment]
https://www.yooasset.com/docs/FAQ 可以参考常见问题里的第二项

**Comment by 9a6c** [comment]
我尝试收集着色器， android编辑器中显示紫色，打出的安卓包真机测试显示紫色， 还在尝试，关于1.确认是否收集过着色器变种，并且SVC文件参与打包。 如何确定它参与了打包呢， 我的办法是放在Resources目录中

**Comment by gmhevinci** [comment]
2.x版本记得勾选auto collect shader选项。打包完成会有一个unityshader.bundle的文件，你可以解开看下

**Comment by 9a6c** [comment]
感谢您的回复！

关于打ab包界面， 后续版本是否考虑支持同时打多个包呢， 目前package1、package2出ab资源，需要一个一个打包

**Comment by gmhevinci** [comment]
> 感谢您的回复！
> 
> 关于打ab包界面， 后续版本是否考虑支持同时打多个包呢， 目前package1、package2出ab资源，需要一个一个打包

主要是unity引擎不支持。

**Comment by 9a6c** [comment]
unity2021.3.6f1 urp

您好， 我尝试使用1.5.7版本 ab包加载是正常的， 但是使用2.x最新版本，加载的ab资源是紫粉色的，下图是1.5.7版本的效果，紫粉色是场景中摆放的东西，ab资源加载的内容正常显示，切换到2.x版本，当前正常显示的内容是紫粉色，请问2.x版本和1.5.7版本有什么区别呢？
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/851a33b9-5a16-49f1-810c-7e7afd67d620)

**Comment by 9a6c** [comment]
补充信息

1.5.7版本出的ab资源包
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/9b72b24f-c2a3-47cf-b358-3f62985fdf6e)

2.x版本出的ab资源包
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/b573b19f-97fa-4482-94e1-5e53c93806e7)

**Comment by gmhevinci** [comment]
上面的信息不足以排查问题原因，你可以进社区QQ群963240451，然后私聊我。
