### ISSUE TITLE
如果AB包中没有变体A，但是Resources有变体A，那AB包中的情况资源可以正常使用变体A吗

### ISSUE THREAD

**Issue by RouderSky** [tuyoogame/YooAsset#242]
其实是想知道是不是AB的shader的变体进AB包，Resources的shader的变体进Resources包

感觉Unity的变体管理好混乱

**Comment by gmhevinci** [comment]
> 其实是想知道是不是AB的shader的变体进AB包，Resources的shader的变体进Resources包
> 
> 感觉Unity的变体管理好混乱

是这样的。如果想热更新，还是使用AB来构建收集变种。
