### ISSUE TITLE
Unity中国版本 团结引擎下Open harmony平台支持计划 

### ISSUE THREAD

**Issue by alex520lq** [tuyoogame/YooAsset#248]
现在使用Addressable在OpenHarmony下无感使用。切换到YooAsset，加载资源路径显示不对。有计划处理吗？

**Comment by gmhevinci** [comment]
后续版本会修改路径问题。

**Comment by gmhevinci** [comment]
> 现在使用Addressable在OpenHarmony下无感使用。切换到YooAsset，加载资源路径显示不对。有计划处理吗？

代码已经上传，请关注后续版本发布。https://github.com/tuyoogame/YooAsset/commit/4c619778c31cfb989dd401a44bba200878f2b482
