### ISSUE TITLE
礼问以下范例里为什么各个操作前面都要加一个WaitForSecondsRealtime呢？

### ISSUE THREAD

**Issue by Odaimoko** [tuyoogame/YooAsset#256]
https://github.com/search?q=repo%3Atuyoogame%2FYooAsset%20WaitForSecondsRealtime&type=code

**Comment by gmhevinci** [comment]
这个是方便开发者能够看清操作流畅，防止过快的一闪而过。没有别的意义

**Comment by Odaimoko** [comment]
好的，感谢解答！
