### ISSUE TITLE
Webgl平台，下载时调用加载接口报错。

### ISSUE THREAD

**Issue by fkwz** [tuyoogame/YooAsset#260]
调用 YooAssets.CreateResourceDownloader接口下载。
下载过程中调用YooAssets.LoadAssetAsync，来加载正在下载的同一个资源。会报AssetBundle file is invalid。

原因是LoadAssetAsync中会引用YooAssets.CreateResourceDownloader中创建的downloader，这个downloader里面AssetBundleWebRequest的_getAssetBundle字段为始终为false，导致LoadAssetAsync拿不到bundle资源。

**Comment by gmhevinci** [comment]
2.2版本里用新的文件系统，该问题不再存在。
