### ISSUE TITLE
请求更新文档

### ISSUE THREAD

**Issue by UriPomer** [tuyoogame/YooAsset#262]
文档中很多内容已经过时了，网上一些教程代码中的一些函数直接消失而非改名。Space Shooter中使用第三方库，阅读起来对新手十分不友好

**Comment by gmhevinci** [comment]
非常抱歉，我会尽快更新官方主页的文档。

**Comment by UriPomer** [comment]
十分感谢。目前这个状态想要搞懂怎么使用，还是要去看示例项目里的第三方框架的源码才行，比较花时间。对着官方文档做也会踩到坑。

**Comment by UriPomer** [comment]
这边还有两个问题，请教一下。
1. File Name Style 选择 HashName 打包失败，其他两种可以，请问大概是哪方面的原因，报错如下：
![image](https://github.com/tuyoogame/YooAsset/assets/48641000/c55b2723-d9a8-41fd-8a84-ca721c37faa1)
还伴随着几个这样的报错：
![image](https://github.com/tuyoogame/YooAsset/assets/48641000/df8f5266-17b9-46cb-82d3-aa2ff3e0dea6)


2. LoadRawFileAsync 方法无法加载 DLL ，我想结合 HybridCLR 一起使用，捣鼓过程中遇到了这个问题，
![image](https://github.com/tuyoogame/YooAsset/assets/48641000/9c0000dd-b384-4339-97c7-c8ae9e045731)
感觉大概是这方面的问题，PipeLine 对应不上，但我的包中除了 RawFile 还有其他的资源，不能使用 RawFileBuildPipeLine
![image](https://github.com/tuyoogame/YooAsset/assets/48641000/4b703961-0344-40b1-bd60-e1dab76eb5bf)
在初始化代码中，这里似乎也需要预先指定 PipeLine。
我好像无法做到同时使用 BulitInPipeLine 和 RawFilePipeLine，如果我想加载 DLL ，是否应该使用两个包（根据网上的教程通常只使用了一个包，自己试了一下用两个包比较麻烦，而且可行性未知）

**Comment by absences** [comment]
使用两个package可以参考我的仓库https://github.com/absences/Unity_HybridCLR_YooAsset_Luban-protobuf3-

如果使用BulitInPipeLine加载dll，使用 LoadAssetAsync也是能加载二进制文件的，
       var handle = loader.LoadAssetAsync("dll");
       await handle;
       var dt = handle.GetAssetObject<TextAsset>();
       Assembly.Load(dt.bytes);

**Comment by gmhevinci** [comment]
> 这边还有两个问题，请教一下。
> 
> 1. File Name Style 选择 HashName 打包失败，其他两种可以，请问大概是哪方面的原因，报错如下：
>    ![image](https://private-user-images.githubusercontent.com/48641000/317659605-c55b2723-d9a8-41fd-8a84-ca721c37faa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDUzNjcsIm5iZiI6MTcxMTcwNTA2NywicGF0aCI6Ii80ODY0MTAwMC8zMTc2NTk2MDUtYzU1YjI3MjMtZDlhOC00MWZkLThhODQtY2E3MjFjMzdmYWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MDY0ZjAyMDVmNjk0ZjA1MmEzZTE1ZjQ5YjA3YjQ1NjM4M2Q2ZWVhMWEwODQxMzNlNTEzZGUwNDliMWRmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFKKxDwRgizZy9KCxi_hWEoqfuMWuZ5x3Sx8XlNkb4M)
>    还伴随着几个这样的报错：
>    ![image](https://private-user-images.githubusercontent.com/48641000/317660050-df8f5266-17b9-46cb-82d3-aa2ff3e0dea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDUzNjcsIm5iZiI6MTcxMTcwNTA2NywicGF0aCI6Ii80ODY0MTAwMC8zMTc2NjAwNTAtZGY4ZjUyNjYtMTdiOS00NmNiLTgyZDMtYWEyZmYzZTBkZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNTBkN2EwMDM5MzAzZDk3NGJmYjQ1ZjVlYTY3Yzg2YjEwZDgxMmFjYjRkNzk4MjI1MGI1MjA1ZGRmM2M0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_XnorIVHTpuHHqn_fighVO85H4Ddgj8Crf5AR1eqY4)
> 2. LoadRawFileAsync 方法无法加载 DLL ，我想结合 HybridCLR 一起使用，捣鼓过程中遇到了这个问题，
>    ![image](https://private-user-images.githubusercontent.com/48641000/317656091-9c0000dd-b384-4339-97c7-c8ae9e045731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDUzNjcsIm5iZiI6MTcxMTcwNTA2NywicGF0aCI6Ii80ODY0MTAwMC8zMTc2NTYwOTEtOWMwMDAwZGQtYjM4NC00MzM5LTk3YzctYzhhZTllMDQ1NzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODkxNTcyNTRhOWU3Njg5YzRiZTljNTBmNTczNmRiYjAxNDA1NGJlNjMwYTlhMmJmMjY1YmIxM2Y5MjA0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0QBlZV0VfxFWko6lBJTl7UfSClvkcdFotgxJafmPp6Q)
>    感觉大概是这方面的问题，PipeLine 对应不上，但我的包中除了 RawFile 还有其他的资源，不能使用 RawFileBuildPipeLine
>    ![image](https://private-user-images.githubusercontent.com/48641000/317656727-4b703961-0344-40b1-bd60-e1dab76eb5bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDUzNjcsIm5iZiI6MTcxMTcwNTA2NywicGF0aCI6Ii80ODY0MTAwMC8zMTc2NTY3MjctNGI3MDM5NjEtMDM0NC00MGIxLWJkNjAtZTFkYWI3NmViNWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYTQwZWI2ZGEzNjM5N2FkNzU0NmQyZTY0M2EwODM1NDc0OGIxMDA3NWVjNjExYmM3OWRkNjU4ODVlODc3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._39HaFUieKfq4Cv4Tp4cny8RzfFW5ZgiGxVWn0m0ud8)
>    在初始化代码中，这里似乎也需要预先指定 PipeLine。
>    我好像无法做到同时使用 BulitInPipeLine 和 RawFilePipeLine，如果我想加载 DLL ，是否应该使用两个包（根据网上的教程通常只使用了一个包，自己试了一下用两个包比较麻烦，而且可行性未知）

第二个问题，楼上已经给出答案了。
我们来讨论第一个问题。根据日志看是反序列化清单抛出的异常：manifest.BundleDic2.Add(packageBundle.FileName, packageBundle);
如果FileNameStyle选择HashName，那么FileName就是哈希值名称.bundle
根据日志里的信息清单里的哈希值似乎为空。这个需要你给我提供一个可以复现的工程。可以加QQ群，然后私聊我。

**Comment by UriPomer** [comment]
这个问题我自己尝试复现的过程中，遇到了一些情况：
1. 首先我从Plastic SCM 版本管理中克隆了一份新的项目，把项目文件夹命名为YooAssetTest，结果打包成功，于是我继续往下尝试能否复现
2. 然后我直接把原来的项目打包成zip，解压到一个叫YooAssetTest的文件夹下，然后尝试打包，结果还是打包成功。这个时候我开始注意到不对劲，我发现我的项目名中有空格。
3. 针对上面发现的空格问题，我更改文件夹名为Yoo Asset Test，然后打包，依然成功
4. 怀疑是缓存之类的问题，我把项目删掉，然后重新创建一个名为Yoo Asset Test的文件夹，再把zip解压进去，然后打包，还是成功
5. 最后一次尝试成功复现：我创建了一个新文件夹，名为【我原来的项目名称】 2，然后打包，报错结果一样，打包失败。感觉不是单纯的空格问题。
我现在申请加入qq群然后把zip（1.65G）发给您

**Comment by UriPomer** [comment]
> 使用两个package可以参考我的仓库 https://github.com/absences/Unity_HybridCLR_YooAsset_Luban-protobuf3-
> 
> 如果使用BulitInPipeLine加载dll，使用 LoadAssetAsync也是能加载二进制文件的，
> 
> ```
> var handle = loader.LoadAssetAsync("dll");
> await handle;
> var dt = handle.GetAssetObject<TextAsset>();
> Assembly.Load(dt.bytes);
> ```

好的十分感谢

**Comment by gmhevinci** [comment]
官方文档现在已经分版本了。可以在主页里切换1.5x, 2.1x, 2.2x三个版本
