### ISSUE TITLE
[需求] 打包界面

### ISSUE THREAD

**Issue by 9a6c** [tuyoogame/YooAsset#263]
打包界面，增加一个选项
指定v1.0存在的情况下，先删除在进行打包
![image](https://github.com/tuyoogame/YooAsset/assets/51264840/27e4a0db-e479-4ed1-a696-670b0c8afb41)

目前我经常使用v1.0进行打包， 每次都需要手动删除，然后进行打包

**Comment by gmhevinci** [comment]
不太建议本地测试的时候，经常使用同一个版本号，构建系统默认使用的时间戳作为版本号。这样可以防止缓存的版本冲突，而不好发现这类隐秘的BUG。

**Comment by 9a6c** [comment]
好的
