### ISSUE TITLE
Editor下，PlayMode 关闭reload Domain,第二次进入游戏走资源加载流程，会卡住

### ISSUE THREAD

**Issue by a313008430** [tuyoogame/YooAsset#273]
![image](https://github.com/tuyoogame/YooAsset/assets/14144317/7599fa98-aa0a-4111-9867-1d858ceb9815)
这里的回调不会走回来

导致这里不返回状态
![43f40f9a2c0e4cc4098e8f34c091f858](https://github.com/tuyoogame/YooAsset/assets/14144317/b2d5681a-badf-46d8-b960-93c1a947c86d)

**Comment by a313008430** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/14144317/58589668-7e8b-4f92-aed3-490cb63cefd9)
我暂时找到的原因是在unity切到webgl平台开发游戏，在关闭editor的时候，释放所有资源 ，全走到这里，然后因为只判定了webgl平台，所以会直接抛错出去，导致后面的逻辑走不下去，资源无法释放

**Comment by gmhevinci** [comment]
在2.2版本ForceUnloadAllAssets已经修改为异步方法了。方法名称为：UnloadAllAssetsAsync()

**Comment by a313008430** [comment]
***@***.***发到这个上面！
