### ISSUE TITLE
SBP方式打包SpriteAtlas，精灵散图的Texture会被打入bundle

### ISSUE THREAD

**Issue by gmoonwalk** [tuyoogame/YooAsset#288]
根据官方文档：[图集打包的零冗余解决方案](https://www.yooasset.com/docs/Solution#%E5%9B%BE%E9%9B%86%E6%89%93%E5%8C%85%E7%9A%84%E9%9B%B6%E5%86%97%E4%BD%99%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)
进行设置，如下图：
![企业微信截图_17139657877209](https://github.com/tuyoogame/YooAsset/assets/136217826/b023a41a-00a6-4386-930c-63df2179fdec)
图集和散图通过PackGroup的方式打入default group.bundle并且散图使用StaticAssetCollector方式收集。打包完成后，使用AssetStudio查看default group.bundle，发现其包含了Sprite和Texture2D以及Atlas所有内容。这些散图的Texture对我是无用的。

BuildIn管线下似乎就没有这问题。

在SBP管线下，有办法只包含SpriteAtlas、图集Texture、Sprite信息吗？

**Comment by gmhevinci** [comment]
SBP库的1.21.22版本目前还有BUG，SBP库可以升级到1.21.22版本。

**Comment by gmoonwalk** [comment]
> SBP库的1.21.22版本目前还有BUG，SBP库可以升级到2.1.3版本。

感谢，经你提醒我才发现原来1.21.22不是最新版本....2.1.3需要指定版本号安装。升级以后没有冗余Texture了。

**Comment by haowenliudragonplus** [comment]
指定Manifest中SBP为2.5.1或2.1.3,后，packa-lock中yooasset的依赖SBP版本还是1.21.22，打包还是有冗余，请问是怎么解决的

<img width="696" height="593" alt="Image" src="https://github.com/user-attachments/assets/009c053e-a5eb-46c7-813e-adbae3e8202d" />

<img width="2309" height="1652" alt="Image" src="https://github.com/user-attachments/assets/318a7e7b-ef4b-453a-af25-86d67d6594a0" />

**Comment by ubuntutututu** [comment]
我也遇到了同样得问题，Unity2023.1.22f1 用得 yooAsset 3.0+ 插件，我更新到 SBP2.0.1 依然打包有问题，已经纳入图集的Sprite资源打的share AB包存在冗余的原始图片资源，（atlas 没有勾选buildin） 。之后我用AssetBundleBrower 打了一下没有问题，锁定是 yooAsset 或是 SBP的问题。
