### ISSUE TITLE
EditorHelper中根据guid找uxml有时候会出错

### ISSUE THREAD

**Issue by wang-er-s** [tuyoogame/YooAsset#29]
把package包在Asset和Packages里更换位置，会出现找不到uxml的问题，建议根据名字找
![QQ截图20220730235155](https://user-images.githubusercontent.com/41230338/181924912-c0c89537-4179-4328-9cb8-59342f10906f.png)
这是我改后的，应该会比guid稳定

**Comment by gmhevinci** [comment]
很好的意见~ 我修复一下
