### ISSUE TITLE
WebGl因为version不缓存的原因，导致每次进游戏都会加载读本地缓存的版本，必出一个404,望优化

### ISSUE THREAD

**Issue by a313008430** [tuyoogame/YooAsset#292]
![ad831b22dbe856d51098731b4f3c2750](https://github.com/tuyoogame/YooAsset/assets/14144317/483d753b-5c3e-44ba-97bf-b34a6e3fc047)

**Comment by gmhevinci** [comment]
可以关注2.2版本 专属的微信小游戏文件系统。

**Comment by a313008430** [comment]
***@***.***发到这个上面！
