### ISSUE TITLE
add "delete default yoo folder name “option

### ISSUE THREAD

**Issue by fanhaining** [tuyoogame/YooAsset#293]
This is not necessary
![image](https://github.com/tuyoogame/YooAsset/assets/17611077/d7133c3a-5ff5-47e3-a4b8-088812444c87)

**Comment by gmhevinci** [comment]
2.2版本 已经实现。

**Comment by linky6565** [comment]
![image](https://github.com/user-attachments/assets/006755ae-8dee-4d9b-adf7-6f5584cc0521)
没看到在哪里实现了啊

**Comment by gmhevinci** [comment]
再次确认一下需求：delete default yoo folder name 是出于什么需求呢？删除默认YOO文件夹？

**Comment by linky6565** [comment]
是的，我想打包出来的资源直接在SteammingAsset下，而不是中间隔了一个文件夹

**Comment by gmhevinci** [comment]
明白了。可以配置为空，然后我代码适配一下。

**Comment by linky6565** [comment]
好的。
