### ISSUE TITLE
关于使用YooAsset做本地化方案的问题

### ISSUE THREAD

**Issue by Yuze075** [tuyoogame/YooAsset#300]
我现在的情况是, 在给当前的项目选择资源加载方案和本地化方案. 本地化方案现在考虑的是使用com.unity.localization, 但是看了一下, 这个unity自带的Localization方案默认适配的是Addressable的资源加载方案. 
现在想问下有没有什么支持YooAsset的本地化方案, 或者说YooAsset是否能适配unity的Localization方案呢?

**Comment by gmhevinci** [comment]
写过一个轻量化的，只是文档几乎没有，不过可以在此基础上魔改或学习。源码不是很多。https://github.com/gmhevinci/UniFramework/tree/main/UniFramework/UniLocalization

**Comment by Yuze075** [comment]
好的了解了. 感谢
