### ISSUE TITLE
能支持微信小游戏的WXAssetBundle吗，会更省内存

### ISSUE THREAD

**Issue by zxt5105515** [tuyoogame/YooAsset#301]
WXAssetBundle类似AssetBundle.LoadFromFile()，用流来减少内存占用
参考
https://wechat-miniprogram.github.io/minigame-unity-webgl-transform/Design/UsingAssetBundle.html#%E4%B8%89%E3%80%81%E6%9B%B4%E8%8A%82%E7%9C%81%E5%86%85%E5%AD%98%E7%9A%84wxassetbundle

**Comment by gmhevinci** [comment]
可以关注后续2.2版本打发布。将会通过新增的虚拟文件系统来支持。

**Comment by owllyi** [comment]
请问2.2版本虚拟文件系统，预计在什么时候可以测试啊

**Comment by gmhevinci** [comment]
2.2版本已经发布了。https://github.com/tuyoogame/YooAsset/releases/tag/2.2.0-preview
