### ISSUE TITLE
ab的依赖信息 对应不上

### ISSUE THREAD

**Issue by Chenxi-Peng** [tuyoogame/YooAsset#304]
Unity：2021.3.13f1
yooAsset: 1.5.1

<img width="842" alt="企业微信截图_17159341575910" src="https://github.com/tuyoogame/YooAsset/assets/73510165/bd2d3320-9d86-4907-8e90-a4ecef095e2d">

白色为OutputCache.manifest 

<img width="1896" alt="企业微信截图_1715934203841" src="https://github.com/tuyoogame/YooAsset/assets/73510165/e77678c5-3a2f-4ad2-ae8a-72a82300c902">

黑色为assetbrower插件显示的依赖信息

**Comment by Chenxi-Peng** [comment]
项目比较特殊： 继续测试复现中

**Comment by gmhevinci** [comment]
OutputCache.manifest 是引擎输出的清单。以这个为准。

**Comment by gmhevinci** [comment]
Unity：2021.3.13f1 建议你升级下小版本号，然后使用SBP构建管线。

**Comment by Chenxi-Peng** [comment]
好的，继续测试

**Comment by Chenxi-Peng** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/73510165/11cecf96-e51f-4cce-832e-b72d86539182)
yooasset 升级后还是对不上。
继续测试：升级Unity版本看看。

**Comment by Chenxi-Peng** [comment]
![image](https://github.com/tuyoogame/YooAsset/assets/73510165/c851305a-9dd5-49af-9e57-771008f5a2ac)
 切换到sbp后，依旧对不上。
yooaseet没有输出manifest文件，阅读打包相关源码后，修改代码输出manifest文件，输出文件使用的是Unity源码，可信度比插件要高。
后续再测试一下版本升级后的情况后，该问题可以关闭了。

**Comment by Chenxi-Peng** [comment]
升级Unity2021.3.38后，两者仍旧对不上，但每次sbp build的结果是一致的。应该能确定了，是assetbrower插件的问题。此问题关闭
