### ISSUE TITLE
2.1.2版本，打开SourceCode工程报错，没有ScriptableBuildPipeline 1.21.22版本。我用的团结引擎1.1.4

### ISSUE THREAD

**Issue by pl01898759** [tuyoogame/YooAsset#310]
如题。。。

**Comment by gmhevinci** [comment]
````
#if TUANJIE_1_0_OR_NEWER
            buildTasks.Add(new CreateBuiltInShadersBundle(builtInShaderBundleName));
#else
            buildTasks.Add(new CreateBuiltInBundle(builtInShaderBundleName));
#endif
````
能确认下宏没生效吗

**Comment by 9a6c** [comment]
unity2021.3.39f1   Scriptable Build Pipeline 1.20.2 是不兼容2021版本了吗？ 需要自己安装Scriptable Build Pipeline新版本吗？
![image](https://github.com/user-attachments/assets/b50eb625-2f45-495b-b580-6fb612fe6f00)

**Comment by gmhevinci** [comment]
> unity2021.3.39f1 Scriptable Build Pipeline 1.20.2 是不兼容2021版本了吗？ 需要自己安装Scriptable Build Pipeline新版本吗？ ![image](https://private-user-images.githubusercontent.com/51264840/350941002-b50eb625-2f45-495b-b580-6fb612fe6f00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODU4MjksIm5iZiI6MTcyMTc4NTUyOSwicGF0aCI6Ii81MTI2NDg0MC8zNTA5NDEwMDItYjUwZWI2MjUtMmY0NS00OTViLWI1ODAtNmZiNjEyZmU2ZjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAxNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NDg0MzAwMTk1Yjc4ZGIxNDU5ZmE2MTE1MWM4MjcxMWJkMWQxMDQ3NjlmZjgyNzM4NjAxYmQ5ZGI4MzVmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M8XSxUCPub9AcMrd-vlu4bIw8HD8zT42OgkKSVlMvtY) ![image](https://private-user-images.githubusercontent.com/51264840/350942338-cf06353d-c32d-453a-ad88-e877e5b7409b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODU4MjksIm5iZiI6MTcyMTc4NTUyOSwicGF0aCI6Ii81MTI2NDg0MC8zNTA5NDIzMzgtY2YwNjM1M2QtYzMyZC00NTNhLWFkODgtZTg3N2U1Yjc0MDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAxNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOGZmNDM4NTdhNjFiMjQwNzhmYWM4ZTcwNzcwYjllZDk4MzAwNmZjZGEzMDZlMjE5M2E1NWY4ZDM2NWY4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7wSbanrJ2TIG8Dv3lydlIEuJpwO0qjU_hBPz_ji74ss)

2021引擎通过package manager安装会自动安装依赖的SBP。如果是手动拷贝YOO到项目内，需要自己手动处理下。

**Comment by gmhevinci** [comment]
![QQ_1721786509102](https://github.com/user-attachments/assets/fb91c225-ee4e-4300-be74-ae6fb802cc9d)
Unity2022, Unity2021, Unity2020版本均通过验证。
