### ISSUE TITLE
使用LoadSceneMode.Single加载出来的场景不能被卸载

### ISSUE THREAD

**Issue by JellyHoney** [tuyoogame/YooAsset#315]
假设现在用LoadSceneMode.Single加载出来了场景A，然后用LoadSceneMode.Additive加载出场景B。
Unity的接口是可以把A卸载掉的，这时候B变成了ActiveScene；
YooAsset的接口不支持卸载场景A

**Comment by gmhevinci** [comment]
YOO设计理念是Single模式加载的场景为主场景，只有加载其它主场景才会卸载之前主场景。

**Comment by JellyHoney** [comment]
> YOO设计理念是Single模式加载的场景为主场景，只有加载其它主场景才会卸载之前主场景。

这块有计划改动吗？

**Comment by gmhevinci** [comment]
我尝试修改一下规则。已加入到修改计划里。

**Comment by gmhevinci** [comment]
https://github.com/tuyoogame/YooAsset/commit/8944ec0e028c088f4c4ae56d9e5241968e54d00f
关注后续版本发布
