### ISSUE TITLE
2.2.1-pre版本OfflinePlayMode模式构建项目后，更新新的包时提示Can not found belong file system

### ISSUE THREAD

**Issue by RSJWY** [tuyoogame/YooAsset#321]
项目使用的是示例场景
版本：2.2.1-pre
运行模式：OfflinePlayMode
更新包使用增量构建

编辑器下没任何问题，构建项目后出现此问题
debug查找问题时，DefaultBuildinFileSystem这个类RecordFile函数添加信息时似乎是以BuildinCatalog信息为主

**Comment by gmhevinci** [comment]
2.2.2版本修复了再编辑器下Offline play mode运行错误的问题。

**Comment by gmhevinci** [comment]
有拷贝AB文件到StreamgAssets目录下吗

**Comment by RSJWY** [comment]
> 有拷贝AB文件到StreamgAssets目录下吗

有，我是把yoo打包后的所有文件都进行了拷贝也还是这样。unity版本是2021.3.34f1c1

**Comment by gmhevinci** [comment]
2021，2022 unity引擎BUG，已经修复。

**Comment by nantianliao** [comment]
2019版本提示'AssetDatabase' does not contain a definition for 'SaveAssetIfDirty'

**Comment by gmhevinci** [comment]
> 2019版本提示'AssetDatabase' does not contain a definition for 'SaveAssetIfDirty'

下版本修复
