### ISSUE TITLE
unity版本2022.3.21f1编辑器内catalog是空的

### ISSUE THREAD

**Issue by MCxYY** [tuyoogame/YooAsset#323]
如图：
![NON%T7NB@X4BKR H_VVT UM](https://github.com/user-attachments/assets/4280f933-fdce-4210-9f77-725b66eb24fe)

应该是同一帧重新创建导致resources没检测到资源，路径完全是正确的，我自己使用resources.load就能加载到
![8I2A(IN0{GWOP@IL6AQ15D6](https://github.com/user-attachments/assets/c0e6b67b-f3ac-4753-8965-d403a6fdad8b)

**Comment by MCxYY** [comment]
很奇怪，是我unity版本或设置问题吗，不然应该很多人都会遇到这个阻断问题的

**Comment by gmhevinci** [comment]
https://github.com/tuyoogame/YooAsset/commit/dc119b26c7f46c592b224c449240e63e526b5449 已经修复
