### ISSUE TITLE
文档Task加载方式会报错

### ISSUE THREAD

**Issue by OopsAngela** [tuyoogame/YooAsset#330]
根据文档中Task加载资源方式，结合Space Shooter案例

![image](https://github.com/user-attachments/assets/08ebbd67-95a9-44af-b3c1-aa5e00e0e307)
不使用TestTask() 方法正常加载其他物体，

AssetHandle handle = package.LoadAssetAsync<AudioClip>("music_background");
await handle.Task;
AudioClip audioClip = handle.AssetObject as AudioClip;

Task方式加载报错：
![image](https://github.com/user-attachments/assets/2ef340e7-ba62-4730-9595-06da381f75f2)
报错：IDecryptionServices is null ! when load asset bundle assets_samples_yooasset_2_1_0_space shooter_gameres_audio.bundle!
![image](https://github.com/user-attachments/assets/1b88ad30-e35c-425c-b8bd-ce9e234b7ced)
报错：Failed to load assetBundle : assets_samples_yooasset_2_1_0_space shooter_gameres_audio.bundle

**Comment by 15951836388** [comment]
我 2.2 await handler.Task; 加载GameObject预制是可以的

**Comment by gmhevinci** [comment]
构建的时候选择Offset加密方法，运行时解密没有报错。
````csharp
        // 单机运行模式
        if (playMode == EPlayMode.OfflinePlayMode)
        {
            FileOffsetDecryption decryption = new FileOffsetDecryption();
            var createParameters = new OfflinePlayModeParameters();
            createParameters.BuildinFileSystemParameters = FileSystemParameters.CreateDefaultBuildinFileSystemParameters(decryption);
            initializationOperation = package.InitializeAsync(createParameters);
        }
````

**Comment by gmhevinci** [comment]
这个问题是因为资源构建过程加密了。运行时还没实现解密。
