### ISSUE TITLE
Exception: Not found active package manifest !

### ISSUE THREAD

**Issue by yingran-cn** [tuyoogame/YooAsset#331]
Exception: Not found active package manifest !Exception: Not found active package manifest !
YooAsset.ResourcePackage.DebugCheckInitialize (System.Boolean checkActiveManifest) (at ./Library/PackageCache/com.tuyoogame.yooasset@2.1.1/Runtime/ResourcePackage/ResourcePackage.cs:1140)
YooAsset.ResourcePackage.LoadAssetAsync[TObject] (System.String location, System.UInt32 priority) (at

**Comment by Lafree317** [comment]
怎么解决的啊
