### ISSUE TITLE
文档翻烂了 没发现初始化到底有啥问题 加载资源就报错Can not found active package manifest !

### ISSUE THREAD

**Issue by Hestiny** [tuyoogame/YooAsset#335]
![image](https://github.com/user-attachments/assets/5aa67118-1482-4542-ab64-138fe243885c)
![image](https://github.com/user-attachments/assets/a383d5cb-f8b5-4ee4-a0d0-4e013065818e)
![image](https://github.com/user-attachments/assets/035e4e84-2cd3-4e18-8de6-3921de4632ba)
编辑器和单机都尝试了 都一样 啥问题啊 折腾好久了

**Comment by absences** [comment]
await package.InitializeAsync(param);

 var op = package.RequestPackageVersionAsync();

 await op;

 await package.UpdatePackageManifestAsync(op.PackageVersion);

 //test load
 var handle = package.LoadAssetAsync<Sprite>("Amumu");

**Comment by Lafree317** [comment]
未解决啊

**Comment by S-JQ** [comment]
> await package.InitializeAsync(param);
> 
> var op = package.RequestPackageVersionAsync();
> 
> await op;
> 
> await package.UpdatePackageManifestAsync(op.PackageVersion);
> 
> //test load var handle = package.LoadAssetAsync("Amumu");
> 
> 无论什么模式运行都需要执行RequestPackageVersionAsync UpdatePackageManifestAsync

执行完成之后需要等待一帧，立即Load也有可能出现同样的问题
