### ISSUE TITLE
[Question]2.2.1-preview版本的资源解密是怎么处理

### ISSUE THREAD

**Issue by miuleung** [tuyoogame/YooAsset#337]
如题，新版本的加密如旧，但解密应该怎么处理呢？连IDecryptionServices接口的引用都没有找到。
是要在新的FileSystem内用户自己处理吗？

**Comment by gmhevinci** [comment]
2.2版本的解密接口已经加上了，会在下个版本发布。https://github.com/tuyoogame/YooAsset/commit/d017688416fdfe6539fda2614a56b0360551e1bb

**Comment by miuleung** [comment]
> 2.2版本的解密接口已经加上了，会在下个版本发布。[d017688](https://github.com/tuyoogame/YooAsset/commit/d017688416fdfe6539fda2614a56b0360551e1bb)

原来如此，那我再等等。感谢
