### ISSUE TITLE
[Enhancement]2.2.x版本建议暴露一些获取版本信息的接口

### ISSUE THREAD

**Issue by miuleung** [tuyoogame/YooAsset#338]
如题：2.2.x本本Remote模式下建议多暴露两个接口：
1：获取本地BuildinCatalog中的PackageVersion字段接口，这样就不需用户自己去读取文件获取原始版本信息；
2：获取本地缓存的版本号
综上：如此再加上原有的获取远端最新版本号，就满足了初始版本号、本地缓存版本号、远端最新版本号的获取和比较，方便进行上层版本比对的业务逻辑处理。
PS：或者接口已有，只是我没找到？

**Comment by gmhevinci** [comment]
1：package.RequestPackageVersionAsync() 方法会返回版本信息，如果是offline play mode模式返回内置清单版本，如果是host play mode返回远端最新版本。另外BuildinCatalog文件只是记录内置文件的清单，这个文件是在构建APK的时候自当生成的并放置在了Resources目录下，目前没有接口可以获取到该文件的信息。如果想记录版本信息，可以自己在构建的时候，生成一个类似的记录版本的文件。
2：2.2.x版本开始，本地不再记录上次登录的版本信息，这个可以通过PlayerPrefs来自己记录。
