### ISSUE TITLE
如何实现项目介绍时说的。发布一个偏单机的游戏安装包，在网络畅通的时候，支持正常更新。在没有网络的时候，支持游玩老版本

### ISSUE THREAD

**Issue by alex520lq** [tuyoogame/YooAsset#340]
是需要自己判断网络状态然后切换不同的模式吗？OfflineInitializeYooAsset？HostInitializeYooAsset 还是有什么APi可以自动实现这个能力。如何需要切换有实现样例吗

**Comment by gmhevinci** [comment]
请参考官方文档：https://www.yooasset.com/docs/Solution#%E5%BC%B1%E8%81%94%E7%BD%91%E7%8E%AF%E5%A2%83%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by ApumpK1n** [comment]
如果第一次进游戏就不联网怎么拿到版本信息？看官方文档的代码存在本地也是需要先拉取一次的

**Comment by gmhevinci** [comment]
> 如果第一次进游戏就不联网怎么拿到版本信息？看官方文档的代码存在本地也是需要先拉取一次的

你可以在构建APP的时候，本地里存储一个文件记录首包的版本号

**Comment by ApumpK1n** [comment]
> > 如果第一次进游戏就不联网怎么拿到版本信息？看官方文档的代码存在本地也是需要先拉取一次的
> 
> 你可以在构建APP的时候，本地里存储一个文件记录首包的版本号

好的
