### ISSUE TITLE
版本2.1.2  SBPBuildTasks没有CreateBuiltInBundle方法。unity2021.3.27f1，SBP版本1.20.2。2.2.3-preview也是一样的

### ISSUE THREAD

**Issue by ZJOnline** [tuyoogame/YooAsset#343]
![image](https://github.com/user-attachments/assets/bb75183a-3ec6-4e54-98fd-ce422bde2662)

**Comment by gmhevinci** [comment]
可以通过升级scriptablebuildpipeline库到2.1.4版本

**Comment by ZJOnline** [comment]
![image](https://github.com/user-attachments/assets/294d1b9e-5d9b-414f-947f-249cd91505e4)
有unity版本推荐，所以没升， Ծ‸Ծ

更新：搞错了，是这里没有升级图标和按钮，我以为我这个unity版本最多就用SBP1.20.2，所以没升级到2.1.4
![image](https://github.com/user-attachments/assets/974e4ef2-dd2c-4a69-bd44-c7be3eb3746c)

**Comment by 9a6c** [comment]
如何升级它的版本呢？ 团结1.2.3
![image](https://github.com/user-attachments/assets/f3705e51-b68b-45ac-8632-ff36f45d6a16)
![image](https://github.com/user-attachments/assets/57f046a4-00da-42ae-b562-230b2879cd14)

**Comment by 9a6c** [comment]
而且unity2021 2022 默认都是1.21.x的版本， 为什么需要使用2.1.x的版本呢？

**Comment by gmhevinci** [comment]
为了解决可编程构建管线，sprite atals冗余的bug. 如果SPB的1.2x最新版本已经修复，可以降低到1.2x版本
