### ISSUE TITLE
[Bug]2.2.3-preview host play mode 卡流程

### ISSUE THREAD

**Issue by miuleung** [tuyoogame/YooAsset#344]
2.2.3-preview版本
host play mode

CreateFileSystem流程多了个return，导致创建了BuildinFileSystem后steps没更新卡住了。注释掉正常使用

![图片](https://github.com/user-attachments/assets/16d3e894-16d8-417a-b918-117c3e85f422)

**Comment by gmhevinci** [comment]
感谢反馈，该问题在2.2.4版本修复啦
