### ISSUE TITLE
[Feat]OfflinePlayMode在StreamingAssets直接替换文件

### ISSUE THREAD

**Issue by miuleung** [tuyoogame/YooAsset#345]
能否更新功能，在资源构建完成后可直接在旧的包中替换StreamingAssets下资源，从而省略掉要再次Build主包的流程。

在其他资源管理插件沿用下来的功能挺实用，对于小公司只有少量机器有买正版unity的就很友好

**Comment by gmhevinci** [comment]
可以进群更具体聊下需求吗？QQ二群：654986302

**Comment by miuleung** [comment]
> 可以进群更具体聊下需求吗？QQ二群：654986302

感谢。我在一群，主要可能群内信息被刷掉没看到。

目前YooAsset是这样的流程：
1：打AB包，资源导入StreamingAssets
2：Build主包，OfflinePlayMode运行
3：内容有修改，重复步骤1和2，完成新包输出

期望：
步骤1和2不变，在第三部有内容修改打AB包后，不需要重复第二个步骤，直接将新的AB资源替换之前步骤2打出的主包中StreamingAssets下的资源即可运行。
如此出一个正版主包可以循环使用。因为有些项目前期并不需要更新，是用单机模式输出，后期才会转为HostPlayMode运行。

不知道我描述得是否清晰。如果仍需要详细解析，我再在群内@群主

**Comment by gmhevinci** [comment]
单机模式不支持资源热更的，你还是直接用host play mode吧，如果是偏单机的游戏，可以用弱联网更新方案。
https://www.yooasset.com/docs/Solution#%E5%BC%B1%E8%81%94%E7%BD%91%E7%8E%AF%E5%A2%83%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by SamuelZon258** [comment]
> 单机模式不支持资源热更的，你还是直接用host play mode吧，如果是偏单机的游戏，可以用弱联网更新方案。 https://www.yooasset.com/docs/Solution#%E5%BC%B1%E8%81%94%E7%BD%91%E7%8E%AF%E5%A2%83%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

我懂他意思 我也有这个困扰 有时候只需要替换ab包不想发新包 导出的StreamingAssets中文件会和editor中的内容有变动 手动替换容易出错
