### ISSUE TITLE
WebGL不支持多Package和不支持原生打包管线的原因是什么

### ISSUE THREAD

**Issue by tomh520** [tuyoogame/YooAsset#346]
代码里没有看出明显的限制，求解惑

**Comment by tomh520** [comment]
是因为原生打包用到了一些File接口吗？
但是多Package不支持是什么原因呢？

**Comment by gmhevinci** [comment]
2.2.4版本 webgl平台 已经支持多packaage和原生文件构建管线了。
老版本不支持是因为ForceUnloadAll()方法无法同步导致的。

**Comment by tomh520** [comment]
收到
