### ISSUE TITLE
2.2.3版本 HostPlayMode模式下执行完defaultHostServer后没有执行fallbackHostServer

### ISSUE THREAD

**Issue by xq48799220** [tuyoogame/YooAsset#363]
2.2.3版本，HostPlayMode 模式下，
请求 RequestPackageVersion 与 请求UpdatePackageManifest行为，
在请求defaultHostServer文件失败后，并不会再次请求fallbackHostServer地址。
只会请求一次。。然后就返回结果了。。

**Comment by gmhevinci** [comment]
是这样设计的，当下次再调用时会自动切换到Fallback host server
