### ISSUE TITLE
2.2.4版本断网首次进游戏时，会找不到manifest文件导致load失败

### ISSUE THREAD

**Issue by haowenliudragonplus** [tuyoogame/YooAsset#380]
2.2.4版本断网首次进游戏时，会找不到manifest文件导致Yooasset.load会报 can not found active package manifest，旧版本是有个拷贝内置清单到缓存的操作，现在这个版本没有，麻烦帮扩展一下怎么搞，谢谢~

**Comment by Programmerslovecats** [comment]
YooAsset在Offline模式的时候，会从内置目录(StreamingAsset)加载清单文件，这里统一使用的UnityWebRequest，而UnityWebRequest是会受网络因素影响的，尝试弱网或者断网情况下，从S目录下载资源是会超时和失败的，对于这一部分我这边在打包的时候会把清单放到Resource目录，运行时从Resource目录加载写入到P目录，随后启动YooAsset

**Comment by gmhevinci** [comment]
新增了示例脚本可以提前拷贝内置文件到沙盒目录下
