### ISSUE TITLE
RawFileBuildPipeline build failed !

### ISSUE THREAD

**Issue by OopsAngela** [tuyoogame/YooAsset#384]
突然RawFileBuildPipeline打包失败了。
![image](https://github.com/user-attachments/assets/dd5ef78a-9575-4a3a-9cda-a0b80ded9ef2)
![image](https://github.com/user-attachments/assets/c18f72d6-1558-4814-ad3e-f9f64238d86e)

**Comment by gmhevinci** [comment]
原生文件存在二进制相同的文件了。我优化一下提示，

**Comment by gmhevinci** [comment]
fixed https://github.com/tuyoogame/YooAsset/commit/763054884b6d1426798a5dbfb0d0a8d480598654
