### ISSUE TITLE
AssetBundleCollector.GetAllDependencies可能会得到非构建时所需依赖

### ISSUE THREAD

**Issue by r1n7aro** [tuyoogame/YooAsset#396]
GetAllDependencies中调用了AssetDatabase.GetDependencies这个接口，在我们的项目（2022.3.47f1）中，此接口在查询脚本引用对象时，会返回编辑器中使用的图标，导致打包时将这些仅编辑器资源一起打包。
目前尚未开一个空项目测试不同项目此接口的行为是否相同（
在[文档](https://docs.unity3d.com/ScriptReference/AssetDatabase.GetDependencies.html)中对此接口的描述为
> Note that this function returns all assets that are referenced by the input asset; these references are not necessarily required during the build process.

或许可以把这部分扔到SBP里用ContentBuildInterface相关接口？

**Comment by gmhevinci** [comment]
fixed https://github.com/tuyoogame/YooAsset/commit/9bc05774232a577bc25c0814db6c90f6028f196b
