### ISSUE TITLE
unity2019.4，编辑器模式初始化遇到An error occurred in build task TaskGetBuildMap_BBP

### ISSUE THREAD

**Issue by zcdj1987** [tuyoogame/YooAsset#400]
错误信息日志如下：
An error occurred in build task TaskGetBuildMap_BBP
UnityEngine.Debug:LogError (object)
YooAsset.Editor.BuildLogger:Error (string) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Editor/AssetBundleBuilder/BuildSystem/BuildLogger.cs:30)
YooAsset.Editor.AssetBundleBuilder:Run (YooAsset.Editor.BuildParameters,System.Collections.Generic.List`1<YooAsset.Editor.IBuildTask>,bool) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Editor/AssetBundleBuilder/AssetBundleBuilder.cs:49)
YooAsset.Editor.BuiltinBuildPipeline:Run (YooAsset.Editor.BuildParameters,bool) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Editor/AssetBundleBuilder/BuildPipeline/BuiltinBuildPipeline/BuiltinBuildPipeline.cs:14)
YooAsset.Editor.AssetBundleSimulateBuilder:SimulateBuild (string,string) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Editor/AssetBundleBuilder/AssetBundleSimulateBuilder.cs:31)
System.Reflection.MethodBase:Invoke (object,object[])
YooAsset.EditorSimulateModeHelper:InvokePublicStaticMethod (System.Type,string,object[]) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Runtime/ResourcePackage/PlayMode/EditorSimulateModeHelper.cs:37)
YooAsset.EditorSimulateModeHelper:SimulateBuild (string,string) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Runtime/ResourcePackage/PlayMode/EditorSimulateModeHelper.cs:18)
YooAsset.EditorSimulateModeHelper:SimulateBuild (YooAsset.EDefaultBuildPipeline,string) (at Library/PackageCache/com.tuyoogame.yooasset@2.2.3-preview/Runtime/ResourcePackage/PlayMode/EditorSimulateModeHelper.cs:26)
GameBase/<EditorInitializeYooAsset>d__6:MoveNext () (at Assets/DominoGame/Scripts/GameBase.cs:89)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
GameBase:Awake () (at Assets/DominoGame/Scripts/GameBase.cs:32)

yoo版本2.2.3，SBP版本2.1.5，根据官网初始化例子写的（官网的初始化例子也有BUG，copy丢失字段）

**Comment by gmhevinci** [comment]
2.2.4版本修复了一个卡死BUG。
