### ISSUE TITLE
加载资源时 PackageManifest 获取资源包内主资源列表的GC问题

### ISSUE THREAD

**Issue by 229526881** [tuyoogame/YooAsset#401]
![dc13e2ac1cf1b3a21e4be273f0661939](https://github.com/user-attachments/assets/4ad9d820-d59b-45ff-bdd4-874d4ee9d775)
![b4d69ff6e64c6ee991f5327b832b42ae](https://github.com/user-attachments/assets/5d530efd-19e2-411b-b98d-a3c7c5a196f3)

**Comment by gmhevinci** [comment]
该方法目前只在编辑器下被调用。
