### ISSUE TITLE
2.1.2 版本虽然支持了华为鸿蒙系统 但sbp依赖提高到了2.1.3 而团结引擎最新版只支持sbp到1.21.25

### ISSUE THREAD

**Issue by yicong1406410220** [tuyoogame/YooAsset#408]
2.1.2 版本虽然支持了华为鸿蒙系统 但sbp依赖提高到了2.1.3 而团结引擎最新版只支持sbp到1.21.25 
导致团结引擎并不能使用这个版本的yooasset
![c6f9bc976348c319491ab81ae42df168](https://github.com/user-attachments/assets/a25db09c-ca2d-4415-a477-73c96d8d8df0)
![84e308e809e74066e457e3a4cf1bd54a](https://github.com/user-attachments/assets/b457525d-bdfc-49e1-8cce-e82ae2fe9f95)

**Comment by gmhevinci** [comment]
已经适配了1.x版本的SBP https://github.com/tuyoogame/YooAsset/commit/5f4e1d0b2f63e1fbe2c9eb74aab5341e7770d40a
