### ISSUE TITLE
打包成webgl后运行失败

### ISSUE THREAD

**Issue by RouderSky** [tuyoogame/YooAsset#411]
Access to fetch at 'http://127.0.0.1:8082/CDN/WebGL/v1.0/PackageManifest_DefaultPackage.version?638707136776690000' from origin 'http://localhost:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

unity版本是 2021.3.30f1
yooasset版本是 1.5.6

web服务器是python的http服务器
cdn服务器是hfs

**Comment by RouderSky** [comment]
解决了，给cdn服务器开启了跨域，但是hai's还是无法运行
![fc04bfc126a755cb57d0c5be5f84f45f](https://github.com/user-attachments/assets/ed73e188-2676-4b1b-92b3-98c44a6d9014)

**Comment by gmhevinci** [comment]
> 解决了，给cdn服务器开启了跨域，但是hai's还是无法运行 ![fc04bfc126a755cb57d0c5be5f84f45f](https://private-user-images.githubusercontent.com/18010177/398611204-ed73e188-2676-4b1b-92b3-98c44a6d9014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjMzMDEsIm5iZiI6MTczNTIyMzAwMSwicGF0aCI6Ii8xODAxMDE3Ny8zOTg2MTEyMDQtZWQ3M2UxODgtMjY3Ni00YjFiLTkyYjMtOThjNDRhNmQ5MDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDE0MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNGQ3OWY3NWU2NzJmZTU2ODYzMGE2MDlmODU3ZDc5OTFiMjVkYjNiNWE4YTMxNWU1NWM3ZTg1MDJmZTcxYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.821EPNK9ZikrDCV8Yv_9VTTbxpSyPSBaq63_STJUbZg)

是不是加载了非WebGL平台构建的AB？

**Comment by RouderSky** [comment]
解决了，是因为PatchWindows被我禁止打开，导致部分代码没有执行
