### ISSUE TITLE
单机模式需要支持指定非StremgingAssets目录的资源包加载

### ISSUE THREAD

**Issue by AbsxT0** [tuyoogame/YooAsset#414]
主旨是为了实现在steam平台上的dlc资源拓展。
steam 安装dlc可以把拓展资源下载到指定目录，但似乎不能指定到运行程序的Data文件夹下，所以只能放置到运行程序的同级目录。
现在存在的问题是，基于OfflinePlayMode的运行模式，无法加载非StremgingAssets目录的下的资源包。
![e70ef8addc4382e372f1394784106658](https://github.com/user-attachments/assets/9cc5a780-7e3a-4f9c-a197-eda276c9ee17)

**Comment by gmhevinci** [comment]
需要修改内置文件系统的参数
````csharp
var fileSystemParams = CreateDefaultBuildinFileSystemParameters();
fileSystemParams .AddParameter(FileSystemParametersDefine.DISABLE_CATALOG_FILE, true);
````
