### ISSUE TITLE
如何下载本地没有的Package？

### ISSUE THREAD

**Issue by lvseouren** [tuyoogame/YooAsset#425]
如题。我想实现的功能是这样的：打出来一个空包给用户，再根据不同用户的需要，各自去下载指定的Package内容。

**Comment by gmhevinci** [comment]
初始化package的时候，注意把build file system params设置为空旧可以了。其它走正常初始化流程。下载

**Comment by lvseouren** [comment]
> 初始化package的时候，注意把build file system params设置为空旧可以了。其它走正常初始化流程。下载

请问如何设置呢？看了下InitializeParameters的代码，没找到这个参数

**Comment by gmhevinci** [comment]
2.2x版本支持设置为空。

**Comment by gmhevinci** [comment]
````csharp
private IEnumerator InitPackage()
{
    var createParameters = new HostPlayModeParameters();
    createParameters.BuildinFileSystemParameters = null; //设置为NULL解决报错！
    createParameters.CacheFileSystemParameters = FileSystemParameters.CreateDefaultCacheFileSystemParameters(remoteServices);
    initializationOperation = package.InitializeAsync(createParameters);
    yield return initializationOperation;
}
````

**Comment by lvseouren** [comment]
> ```cs
> s.BuildinFileSystemParam
> ```

抱歉忘了说我用的版本是2.1.0,这个版本需要额外设置吗

**Comment by gmhevinci** [comment]
2.1版本是过度版本，建议升级到最新版本。

**Comment by lvseouren** [comment]
> 2.1版本是过度版本，建议升级到最新版本。

![image](https://github.com/user-attachments/assets/99eb0ee0-fd0d-4f3f-9995-b4de875971bd)
我是跟着文档安装的😂，2.2.x版本咋安装？

**Comment by gmhevinci** [comment]
通过package manager安装
https://www.yooasset.com/docs/guide-editor/QuickStart

**Comment by lvseouren** [comment]
> 通过package manager安装 https://www.yooasset.com/docs/guide-editor/QuickStart

package manager中似乎没有2.2.x版本

**Comment by lvseouren** [comment]
> 通过package manager安装 https://www.yooasset.com/docs/guide-editor/QuickStart

![image](https://github.com/user-attachments/assets/f07e449c-c4d5-41df-a81e-d6412ee55b03)

**Comment by lvseouren** [comment]
感谢解答，勾上这个之后有了
![image](https://github.com/user-attachments/assets/9e1c06da-c096-417c-b746-58da15fc89fe)
