### ISSUE TITLE
AssetsPackage.InitializeAsync初始化失败后需手动找到对应的GameObject后才能销毁，需要添加重试或者销毁操作。

### ISSUE THREAD

**Issue by SuperLin10** [tuyoogame/YooAsset#46]
InitializeAsync，操作需要获取到version文件。在webgl下StreamingAssets也是通过网络下载的，也会出现网络问题导致无法正常下载到。这时会导致初始化失败，需要添加重试或者销毁操作。

**Comment by gmhevinci** [comment]
Offline模式下，WebGL平台在网络异常的情况下，初始化方法里有概率加载version文件或清单文件失败。
