### ISSUE TITLE
提个关于新人上手的小建议

### ISSUE THREAD

**Issue by RouderSky** [tuyoogame/YooAsset#60]
Space Shooter里由于引用了UniFramework、BetterStreamingAssets，查看YooAsset不够直观。

建议制作一个只用YooAsset就可以跑通YooAsset主流程的demo。这个demo展示全部YooAsset的核心功能，也可以有一些比较高级的用法，例如自定义过滤、自定义加密/解密等等。demo不一定要是一个可运行的游戏，演示功能才是重点。

如果有这样一个demo，学习成本会进一步降低，上手越快，用户增长也会越快。

**Comment by gmhevinci** [comment]
了解，我这边会再提供一个更简单的展示实际使用功能的范例
