### ISSUE TITLE
Unity2019.3.2.f1导入报错 

### ISSUE THREAD

**Issue by ohmydone** [tuyoogame/YooAsset#64]
`Assets\YooAsset\Editor\AssetBundleBuilder\BuildTasks\SBPBuildTasks.cs(27,23): error CS0246: The type or namespace name 'CalculateCustomDependencyData' could not be found (are you missing a using directive or an assembly reference?)`

`Assets\YooAsset\Editor\AssetBundleBuilder\BuildTasks\SBPBuildTasks.cs(46,23): error CS0246: The type or namespace name 'GenerateLinkXml' could not be found (are you missing a using directive or an assembly reference?)`

`Assets\YooAsset\Editor\AssetBundleBuilder\BuildParametersContext.cs(116,16): error CS1061: 'BundleBuildParameters' does not contain a definition for 'WriteLinkXML' and no accessible extension method 'WriteLinkXML' accepting a first argument of type 'BundleBuildParameters' could be found (are you missing a using directive or an assembly reference?)`

**Comment by gmhevinci** [comment]
YooAssets插件依赖于SBP可编程构建管线。在package manager里导入SBP即可。

**Comment by ohmydone** [comment]
已经安装了SBP

**Comment by gmhevinci** [comment]
升级unity版本到LTS版本。
