### ISSUE TITLE
[Bug]升级到1.4.4后报错

### ISSUE THREAD

**Issue by huangkumao** [tuyoogame/YooAsset#66]
`**SimulateBuild pipeline build failed !**
UnityEngine.Debug:LogWarning (object)
YooAsset.Editor.AssetBundleBuilder:Run (YooAsset.Editor.BuildParameters) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Editor/AssetBundleBuilder/AssetBundleBuilder.cs:96)
YooAsset.Editor.AssetBundleSimulateBuilder:SimulateBuild (string) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Editor/AssetBundleBuilder/AssetBundleSimulateBuilder.cs:23)
System.Reflection.MethodBase:Invoke (object,object[])
YooAsset.EditorSimulateModeHelper:InvokePublicStaticMethod (System.Type,string,object[]) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/PatchSystem/PlayMode/EditorSimulateModeHelper.cs:30)
YooAsset.EditorSimulateModeHelper:SimulateBuild (string) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/PatchSystem/PlayMode/EditorSimulateModeHelper.cs:18)
Main.GamePatches.GamePatch/<Start>d__3:MoveNext () (at Assets/Scripts/Main/GamePatches/GamePatch.cs:51)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)`

`**Build task failed : TaskPrepare**
UnityEngine.Debug:LogError (object)
YooAsset.Editor.AssetBundleBuilder:Run (YooAsset.Editor.BuildParameters) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Editor/AssetBundleBuilder/AssetBundleBuilder.cs:97)
YooAsset.Editor.AssetBundleSimulateBuilder:SimulateBuild (string) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Editor/AssetBundleBuilder/AssetBundleSimulateBuilder.cs:23)
System.Reflection.MethodBase:Invoke (object,object[])
YooAsset.EditorSimulateModeHelper:InvokePublicStaticMethod (System.Type,string,object[]) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/PatchSystem/PlayMode/EditorSimulateModeHelper.cs:30)
YooAsset.EditorSimulateModeHelper:SimulateBuild (string) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/PatchSystem/PlayMode/EditorSimulateModeHelper.cs:18)
Main.GamePatches.GamePatch/<Start>d__3:MoveNext () (at Assets/Scripts/Main/GamePatches/GamePatch.cs:51)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
`

`**Build task error : System.Exception: Unity2021 or newer not support BuiltinBuildPipeline, Please use ScriptableBuildPipeline**
  at YooAsset.Editor.TaskPrepare.YooAsset.Editor.IBuildTask.Run (YooAsset.Editor.BuildContext context) [0x00023] in E:\Work\WOWFirst\Client\Library\PackageCache\com.tuyoogame.yooasset@1.4.4-preview\Editor\AssetBundleBuilder\BuildTasks\TaskPrepare.cs:21 
  at YooAsset.Editor.BuildRunner.Run (System.Collections.Generic.List`1[T] pipeline, YooAsset.Editor.BuildContext context) [0x0006d] in E:\Work\WOWFirst\Client\Library\PackageCache\com.tuyoogame.yooasset@1.4.4-preview\Editor\AssetBundleBuilder\BuildSystem\BuildRunner.cs:33 
UnityEngine.Debug:LogError (object)
YooAsset.Editor.AssetBundleBuilder:Run (YooAsset.Editor.BuildParameters) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Editor/AssetBundleBuilder/AssetBundleBuilder.cs:98)
YooAsset.Editor.AssetBundleSimulateBuilder:SimulateBuild (string) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Editor/AssetBundleBuilder/AssetBundleSimulateBuilder.cs:23)
System.Reflection.MethodBase:Invoke (object,object[])
YooAsset.EditorSimulateModeHelper:InvokePublicStaticMethod (System.Type,string,object[]) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/PatchSystem/PlayMode/EditorSimulateModeHelper.cs:30)
YooAsset.EditorSimulateModeHelper:SimulateBuild (string) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/PatchSystem/PlayMode/EditorSimulateModeHelper.cs:18)
Main.GamePatches.GamePatch/<Start>d__3:MoveNext () (at Assets/Scripts/Main/GamePatches/GamePatch.cs:51)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
`

`Exception: SimulatePatchManifestPath is null or empty.
YooAsset.AssetsPackage.CheckInitializeParameters (YooAsset.InitializeParameters parameters) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/AssetsPackage.cs:160)
YooAsset.AssetsPackage.InitializeAsync (YooAsset.InitializeParameters parameters) (at Library/PackageCache/com.tuyoogame.yooasset@1.4.4-preview/Runtime/AssetsPackage.cs:80)
Main.GamePatches.GamePatch+<Start>d__3.MoveNext () (at Assets/Scripts/Main/GamePatches/GamePatch.cs:55)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <7b2a272e51214e2f91bbc4fb4f28eff8>:0)
`

编辑器模拟运行 报错
退回1.4.1后正常

**Comment by gmhevinci** [comment]
已修复。
