### ISSUE TITLE
reporter 下面的include assets会显示不全

### ISSUE THREAD

**Issue by mi1890** [tuyoogame/YooAsset#67]
查看报告时如果assetbundle较多,会挤占大部分空间,导致includeassets显示不全
版本:unity2021.3.4 yooassets:1.4.4preview

![image](https://user-images.githubusercontent.com/5334863/219605346-a4c05ba4-0f41-4274-805a-8cb3d188431e.png)

解决办法:
可以考虑修改flex属性,上下listview都改为50%
![E%{5}8BO_53VFU C}SVR@YT](https://user-images.githubusercontent.com/5334863/219605395-5b579a65-4a74-4b15-8d9d-ac9befc535a1.png)

**Comment by gmhevinci** [comment]
在unity2019.4上测试没有问题。不过可以修改下来兼容2021问题

**Comment by BIGWGY** [comment]
使用的 unity版本：2021.1

UnityEngine.UIElements.ListView.rebuild 在 2021.2 版本才有的接口：

![图片](https://github.com/tuyoogame/YooAsset/assets/13144389/de3b260c-671e-480b-9f89-b0abde34ffe3)

![图片](https://github.com/tuyoogame/YooAsset/assets/13144389/1696efbc-e0f3-456e-b74b-9c2932e51334)

![图片](https://github.com/tuyoogame/YooAsset/assets/13144389/fab66c5b-5864-4a38-b700-e6c24ae94e5f)

你们在 2019 安装的时候，怎么会没报错呢？

**Comment by gmhevinci** [comment]
@BIGWGY 你好，可以用unity2021.3试一下吗

**Comment by BIGWGY** [comment]
发现问题，2021.3 是没问题的。 

UnityEngine.UIElements.ListView.rebuild 是 2021.2 才有的， 2021.1 之前是方法名是 refresh，我加了个编译条件，就行了：

![图片](https://github.com/tuyoogame/YooAsset/assets/13144389/887dc734-38ae-4337-9618-807a686812ec)

**Comment by gmhevinci** [comment]
这个问题其实不用处理，2021.3是稳定版。其它版本不用关心

**Comment by BIGWGY** [comment]
嗯
