### ISSUE TITLE
在UnloadUnusedAssets的时候，未考虑bundle间的依赖，导致被依赖的bundle unload之后，重新load回来，bundle中资源依赖关系丢失，导致显示问题

### ISSUE THREAD

**Issue by JianWangUStar** [tuyoogame/YooAsset#75]
一个简单的例子
Prefab PA,PB
Material MA,MB
Texture TA,TB
PA依赖MA,MB
PB依赖MB
MA依赖TA，
MB依赖TB

PA 打bundle到 bundle_PA中
PB打bundle到 bundle_PB中

MA,MB 打bundle到 bundle_MAT中

TA 打bundle到 bundle_TA中
TB打bundle到 bundle_TB中

PA 依赖 bundle_PA,bundle_MAT,bundle_TA,bundle_TB
PB 依赖 bundle_PB,bundle_MAT,bundle_TB

在游戏中实例PA，PB后，销毁PA,然后调用UnloadUnusedAssets，会让bundle_TA，bundle_PA卸载，bundle_MAT由于有PB引用，未卸载

再次实例PA之后，会重新加载bundle_TA，bundle_PA，而bundle_MAT在内存中不用重新加载，这个之后，就算重新加载了bundle_TA，但是bundle_MAT对bundle_TA的依赖关系却不能恢复，导致从bundle_MAT获取的MA的贴图TA丢失，

**Comment by gmhevinci** [comment]
这个问题已经在1.4.7版本修复。您可以验证一下。

**Comment by JianWangUStar** [comment]
okok

**Comment by gmhevinci** [comment]
@xukunn1226 之前想过这个办法，但是考虑到复杂度和计算量就放弃了。SBP提供的依赖列表在运行时不会有太大影响。

**Comment by gmhevinci** [comment]
后面我还会研究下，在构建build map的时候，把引用关系创建出来。
