### ISSUE TITLE
AssetBundleFileLoader 文件下载失败无限重试

### ISSUE THREAD

**Issue by HXiaoMing** [tuyoogame/YooAsset#79]
AssetBundleFileLoader 有一段这样的代码
```
// 1. 从服务器下载
if (_steps == ESteps.Download)
{
	int failedTryAgain = int.MaxValue;
	_downloader = DownloadSystem.BeginDownload(MainBundleInfo, failedTryAgain);
	_steps = ESteps.CheckDownload;
}
```

int failedTryAgain = int.MaxValue;
如果文件一直下载失败，就会一直重试

可不可以使用CreatePatchDownloader 时传进去的failedTryAgain这个参数？

下面几个类也有类似的实现
![02CD52996CBDED61CEDF03A302434F26](https://user-images.githubusercontent.com/22089782/225570830-09e7b838-f037-4cfc-8218-657976a84f07.jpg)

**Comment by HXiaoMing** [comment]
> AssetBundleFileLoader 有一段这样的代码
> 
> ```
> // 1. 从服务器下载
> if (_steps == ESteps.Download)
> {
> 	int failedTryAgain = int.MaxValue;
> 	_downloader = DownloadSystem.BeginDownload(MainBundleInfo, failedTryAgain);
> 	_steps = ESteps.CheckDownload;
> }
> ```
> 
> int failedTryAgain = int.MaxValue; 如果文件一直下载失败，就会一直重试
> 
> 可不可以使用CreatePatchDownloader 时传进去的failedTryAgain这个参数？
> 
> 下面几个类也有类似的实现 ![02CD52996CBDED61CEDF03A302434F26](https://user-images.githubusercontent.com/22089782/225570830-09e7b838-f037-4cfc-8218-657976a84f07.jpg)

**Comment by gmhevinci** [comment]
下个版本会提供一个参数来控制重试次数。
