### ISSUE TITLE
OperationSystem 的更新逻辑有可能导致某个异步操作无限持续下去。

### ISSUE THREAD

**Issue by xxl-game** [tuyoogame/YooAsset#96]
Update中，遍历 operations 列表， 对每个 operation 执行 Update() 之后，已完成的 operation 会被添加到一个 removeList 中，再遍历 operations 列表，把标记为 remove 的移除掉。这种写法应该是为了避免在遍历的过程中删除元素导致的元素序号错误问题。

但考虑以下情况：

当一个 operation 执行 Update 之后处于完成状态时，接下来会调用 operation.Finish() ，如果回调函数中的业务有例如报空这样的错误，导致 operation.Finish() 直接断掉，那么这个已完成的 operation 就不会被删除掉。接下来的每一帧都卡在这里不停的循环 Update -> Finish -> Update -> Finish ......不停的每帧触发更新和完成回调，永远无法被清理掉。

我在业务中遇到了这个问题，虽然在业务里也可以通过判空或者 try catch 等手段来规避这个问题，但还是觉得，由于外部业务的报错导致底层的异步操作永远无法退出这个做法有点不合理。 operation 每帧不停更新，到 Finish 之后，理论上就应该完全结束了，无论这个完成回调的 callback 怎样，是顺利完成还是有错误，这个异步操作都应该彻底结束并被删除。

因此，个人理解，这里可以改变一下逻辑，几种做法：

1.  把 移除 removeList 的操作放到更新所有异步之前。这样已经完成的操作一定会被删除，只是会延后一帧。
2.  用 for 循环去更新，完成一个就立即删除一个，然后手动修改序号，先删除再执行 Finish。
3.  在调用 operation.Finish 的时候 try catch 一下。

```
public static void Update()
{
	_frameTime = _watch.ElapsedMilliseconds;
	// 添加新的异步操作
	if (_addList.Count > 0)
	{
		for (int i = 0; i < _addList.Count; i++)
		{
			var operation = _addList[i];
			_operations.Add(operation);
		}
		_addList.Clear();
	}
	// 更新所有的异步操作
	foreach (var operation in _operations)
	{
		if (IsBusy)
			break;
		operation.Update();
		if (operation.IsDone)
		{
			_removeList.Add(operation);
			operation.Finish();  // 这里回调函数内部报空，逻辑从这里中断。下面的移除逻辑执行不到。
		}
	}

	// 移除已经完成的异步操作
	if (_removeList.Count > 0)
	{
		foreach (var operation in _removeList)
		{
			_operations.Remove(operation);
		}
		_removeList.Clear();
	}
}
```

**Comment by gmhevinci** [comment]
你好，同学，Complete回调的业务逻辑发生异常，确实会导致这个问题。非常感谢提供的信息。

**Comment by gmhevinci** [comment]
可以更新到1.4.10 版本，应该是修复了

**Comment by xushunwang** [comment]
原本1.5.4-preview到1.5.5-preview pick了这个修改，导致下面的写法出错了。
```
if (playMode == EPlayMode.HostPlayMode)
        {
            var createParameters = new HostPlayModeParameters();
            createParameters.DecryptionServices = new GameDecryptionServices();
            
            createParameters.BuildinQueryServices = new GameBuildinQueryServices();
            createParameters.DeliveryQueryServices = new GameDeliveryQueryServices();

            createParameters.RemoteServices = new RemoteServices(string.Empty, string.Empty, string.Empty, string.Empty);
            createParameters.DownloadFailedTryAgain = 3;
            //createParameters.DownloadTimeout
            initializationOperation = package.InitializeAsync(createParameters);
        }

        await initializationOperation.Task;
        if (initializationOperation.Status == EOperationStatus.Succeed)
        {
            Debug.Log($"初始化成功");

            //下面这行会报错：package未初始化
            label.text = package.GetPackageVersion();//initializationOperation.PackageVersion;
        }
        else
        {
            Debug.LogError($"初始化失败");
        }
```

看了下提交，是这个callback执行顺序调整导致的
![图片](https://github.com/tuyoogame/YooAsset/assets/3183025/bbd6ae77-c0b2-46fb-abd7-98a77264b9b7)

**Comment by gmhevinci** [comment]
确实会有问题。我修复下

**Comment by EP-Toushirou** [comment]
> 可以更新到1.4.10 版本，应该是修复了

在_callback?.Invoke(this)那里加个try catch包着会不会更优呢

**Comment by gmhevinci** [comment]
> > 可以更新到1.4.10 版本，应该是修复了
> 
> 在_callback?.Invoke(this)那里加个try catch包着会不会更优呢

底层 尽量不去捕获业务逻辑端的异常。
