### ISSUE TITLE
ShaderVarient Collector 无法保存设置

### ISSUE THREAD

**Issue by DevSimp2023** [tuyoogame/YooAsset#97]
![T$S}1RL GD(BY$AW`X$8 }U](https://user-images.githubusercontent.com/126373514/231731642-1bc3994e-f29c-412a-9478-dc645b9e0abb.jpg)
每次重开编辑器都会还原成默认值

**Comment by DevSimp2023** [comment]
对了 版本是 1.4.10

**Comment by gmhevinci** [comment]
unity版本是多少？这边没有复现。
