### ISSUE TITLE
默认生成的AssetBundleBuilderSetting之类的文件存放在能否可以自定义目录？

### ISSUE THREAD

**Issue by SilkageNet** [tuyoogame/YooAsset#99]
默认生成的AssetBundleBuilderSetting之类的文件存放在能否可以自定义目录？

或者可以放入一个统一的YooAsset目录里，而不是散落在根目录下呢？

**Comment by gmhevinci** [comment]
配置文件的位置，可以随意放。只要同一个工程里，不要同时存在多个即可。

**Comment by SilkageNet** [comment]
> 配置文件的位置，可以随意放。只要同一个工程里，不要同时存在多个即可。

OK，我明白了，不过仍期望在通过菜单栏默认创建的时候可以指定一个官方目录。

**Comment by gmhevinci** [comment]
你的意见采纳啦。下个版本就有了 。
